Theseus-Aegis/Mods

addons/shootingrange/CfgVehicles.hpp
addons/shootingrange/functions/fnc_create.sqf
addons/shootingrange/functions/fnc_popupPFH.sqf
addons/shootingrange/functions/fnc_popupPFHexit.sqf
addons/shootingrange/functions/fnc_start.sqf
addons/shootingrange/functions/fnc_stop.sqf
addons/shootingrange/script_component.hpp
addons/shootingrange/stringtable.xml

Close #118 
Rampage mode pops up all targets and displays targets hit out of all targets in specified time limit.

Add Rampage mode to shooting range

---

optionals/tban_armed/CfgVehicles.hpp

- Fix #131 
- Add backpack to 2 TBan units
- Put RPG rounds into it
- RPT warning shows up even when the round goes directly into the weapon, so it's not loaded by default now

Fix TBan Armed magazines not stored in vest or uniform RPT warnings

---

addons/shootingrange/CfgAnimationSourceSounds.hpp
addons/shootingrange/CfgVehicles.hpp
addons/shootingrange/config.cpp
addons/shootingrange/functions/fnc_animateTarget.sqf
addons/shootingrange/functions/fnc_handleHitPart.sqf
addons/shootingrange/functions/fnc_start.sqf
addons/shootingrange/functions/fnc_stop.sqf

- Adds sound effects to shooting range on:
- Target hit
- Target pops up/down
- Course start
- Course countdown
- Course finish
- Closes #135

Add sound effects to shooting range

---

addons/bodybag/$PBOPREFIX$
addons/bodybag/CfgEventHandlers.hpp
addons/bodybag/CfgVehicles.hpp
addons/bodybag/README.md
addons/bodybag/XEH_PREP.hpp
addons/bodybag/XEH_postInit.sqf
addons/bodybag/XEH_preInit.sqf
addons/bodybag/XEH_preStart.sqf
addons/bodybag/config.cpp
addons/bodybag/functions/fnc_moveInventory.sqf
addons/bodybag/functions/fnc_placeDroppedWeapons.sqf
addons/bodybag/functions/fnc_saveDroppedWeapons.sqf
addons/bodybag/functions/script_component.hpp
addons/bodybag/script_component.hpp

- Adds body bag inventory transferring - Closes #89 
- Adds inventory to body bag with only 1 unit of space (`addXCargo` commands ignore available space and body bags can't be used as transport boxes)
- Moves all inventory from dead body being placed into a body bag into the body bag's inventory
- Replaces dropped primary weapon and launcher on the ground near the body bag (`deleteVehicle` removes it, but there is no way to get the reference to it from the dead body)

Add bodybag inventory transferring

---

addons/shootingrange/CfgVehicles.hpp
addons/shootingrange/XEH_PREP.hpp
addons/shootingrange/functions/fnc_create.sqf
addons/shootingrange/functions/fnc_handleHitPart.sqf
addons/shootingrange/functions/fnc_moduleInit.sqf
addons/shootingrange/functions/fnc_playSoundSignal.sqf
addons/shootingrange/functions/fnc_start.sqf
addons/shootingrange/functions/fnc_stop.sqf
addons/shootingrange/stringtable.xml

- Add option for multiple sound sources - close #160 
- Play sound hints on all controllers

Add option for multiple sound sources

---

addons/air_security/config.cpp
addons/armory/config.cpp
addons/bodybag/config.cpp
addons/difficulties/config.cpp
addons/headless/config.cpp
addons/heavylifter/config.cpp
addons/insignia/config.cpp
addons/main/config.cpp
addons/misc/config.cpp
addons/radios/config.cpp
addons/ratelmarker/config.cpp
addons/resources/config.cpp
addons/shootingrange/config.cpp
addons/zeus/config.cpp
extras/blank/config.cpp
optionals/compat_cha_av8b/config.cpp
optionals/compat_rhsafrf/config.cpp
optionals/compat_rhsusf/config.cpp
optionals/tban_armed/config.cpp

- Close #173 
- Fix `author/ is not a value`
- Convert `author[]` to `authors[]`
- Add `author` entry with value `ECSTRING(main,Author)`/`CSTRING(Author)`
- Add `url` entry with value `"http://www.theseus-aegis.com/"`
- Fix missing space in front of `=` in `author[]`
- Update `blank` component as well
**Converting `author[]` to `authors[]`:**
Find:
```
author\[\]= {([\s\S]*?)};
```
Replace:
```
authors\[\] = {$1};
```
**Adding `author` and `url`:**
Find:
```
class CfgPatches([\s\S]*?);([\s]*?)authors\[\]
```
Replace:
```
class CfgPatches$1;\n        author = ECSTRING\(main,Author\);$2authors\[\]
class CfgPatches$1;\n        url = "http://ace3mod.com";$2authors\[\]
```

Convert CfgPatches authors for 1.60

---

addons/armory/XEH_PREP.hpp
addons/armory/functions/fnc_dialogControl_list.sqf
addons/armory/functions/fnc_dialogControl_populateList.sqf
addons/armory/functions/fnc_extractSubCategories.sqf
addons/armory/functions/fnc_getDataVanilla.sqf
addons/armory/functions/fnc_isCompatible.sqf
addons/armory/script_component.hpp
addons/armory/stringtable.xml

- Fixes list tooltips
- Work on #84 
- Adds "Compatible" sub-category which shows only ammo/attachments compatible with weapons in player's inventory
- Changes vanilla data debug work with `DEBUG_MODE_FULL` macro

Add Armory compatible items sub-category and fix tooltips

---

addons/shootingrange/CfgVehicles.hpp
addons/shootingrange/XEH_preInit.sqf
addons/shootingrange/functions/fnc_addConfigDurations.sqf
addons/shootingrange/functions/fnc_addConfigPauseDurations.sqf
addons/shootingrange/functions/fnc_addConfigTargetAmounts.sqf
addons/shootingrange/functions/fnc_animateTarget.sqf
addons/shootingrange/functions/fnc_canActivateTrigger.sqf
addons/shootingrange/functions/fnc_checkConfig.sqf
addons/shootingrange/functions/fnc_create.sqf
addons/shootingrange/functions/fnc_handleHitPart.sqf
addons/shootingrange/functions/fnc_moduleInit.sqf
addons/shootingrange/functions/fnc_popupPFH.sqf
addons/shootingrange/functions/fnc_popupPFHexit.sqf
addons/shootingrange/functions/fnc_start.sqf
addons/shootingrange/functions/fnc_stop.sqf
addons/shootingrange/functions/fnc_triggerPopup.sqf
addons/shootingrange/script_component.hpp
addons/shootingrange/stringtable.xml

- Close #103 
- Fix trigger activation during countdown
- Fix config check
- Replace vanilla `hitPart` function with `handleHitPart`
- Remove usage of `nopop` and use custom variable (possible due to custom `hitPart` handling)
- Revert animation changes to work without delays (possible due to custom `hitPart` handling and actually caused issues)
- Add setting for number of hits necessary per target
- Add setting for showing hitshint (number of hits out of number of hits necessary for target to pop down)
- Use `apply` in module init

Add multiple hit setting to shooting range targets

---

addons/insignia/functions/fnc_setInsignia.sqf

- Fix insignia not applying except in init.
- `BIS_fnc_getUnitInsignia` actually returns whatever was set with `BIS_fnc_setUnitInsignia` instead of what is currently visible.

Fix insignia not applying

---

optionals/melb_ace_fastroping/$PBOPREFIX$
optionals/melb_ace_fastroping/CfgVehicles.hpp
optionals/melb_ace_fastroping/README.md
optionals/melb_ace_fastroping/config.cpp
optionals/melb_ace_fastroping/script_component.hpp
optionals/melb_eject/$PBOPREFIX$
optionals/melb_eject/CfgVehicles.hpp
optionals/melb_eject/README.md
optionals/melb_eject/config.cpp
optionals/melb_eject/script_component.hpp

- Allow ejection from MELB's copilot and pilot seats - close #220.
- Add ACE3 Fastroping support to MELB MH6 - close #218.

Add MELB (co)pilot ejection and ACE3 fastroping optionals

---

addons/shootingrange/CfgEventHandlers.hpp
addons/shootingrange/XEH_postInit.sqf
addons/shootingrange/XEH_postInitClient.sqf
addons/shootingrange/functions/fnc_stop.sqf

- Close #214 
- Log result on successful shooting range completion on server and the client who finished it.
Example:
```
1:29:52 [TAC] (shootingrange) INFO: Shooting Range (Oval Test) Finished. Accuracy: 94% (15/16). Time Elapsed: 3.917s. By: Dev
```

Log shooting range results to RPT

---

addons/shootingrange/CfgVehicles.hpp
addons/shootingrange/functions/fnc_create.sqf
addons/shootingrange/functions/fnc_handleHitPart.sqf
addons/shootingrange/functions/fnc_moduleInit.sqf
addons/shootingrange/functions/fnc_popupPFH.sqf
addons/shootingrange/functions/fnc_triggerPopup.sqf
addons/shootingrange/script_component.hpp
addons/shootingrange/stringtable.xml

- Remove multiple hit from shooting range (introduced in #179), as it is no longer used and will not be used (only maintenance and possible bug causer).
- Deprecate `hits` and `showHits` parameters in public `tac_shootingrange_fnc_create` function (by simply leaving empty)
- Maybe fixes weird pop-up, not popping down issues.

Remove multiple hit from shooting range

---

addons/insignia/ACE_Settings.hpp
addons/insignia/config.cpp
addons/insignia/functions/fnc_getInsignia.sqf
addons/insignia/functions/fnc_setInsignia.sqf

- Title
Should help figure out if the "Theseus pants" bug is the cause of automatic insignia application (happens too early during unit creation or something).

Add insignia enabled setting

---

addons/heavylifter/CfgVehicles.hpp
optionals/compat_cup_vehicles/CfgVehicles.hpp

- Update `cup_compat_vehicles` for CUP 1.9.1
- Update Heavy Lifter positions for vanilla 1.72 (also moves some positions from CUP due to only CUP definitions update previously)

Update Heavy Lifter definitions for Arma 3 1.72 and CUP 1.9.1

---

addons/air_security/README.md
addons/air_security/functions/fnc_setSecurity.sqf

- Close #313 
CUP helicopters have actions for doors, ACE3 Fastroping automatically opens and closes doors.

Remove door opening/closing in Air Security

---

addons/shootingrange/functions/fnc_textsIntoLocalizedString.sqf

Fix texts into localized string script error when passing non-string type

---

addons/armory/XEH_postInitClient.sqf
addons/armory/functions/fnc_processAction.sqf

- Fix #321
- Add delay to full refresh of box contents until player stops stashing for a second

Fix full refresh box contents duplicating items

---

addons/shootingrange/functions/fnc_textsIntoLocalizedString.sqf

- Fix an issue where strings name would appear with double quote instead of being localized after finishing a course.

Fix strings being stringified a second time in textsIntoLocalizedString

---

addons/cba_settings/README.md
addons/insignia/CfgEventHandlers.hpp
addons/insignia/XEH_clientInit.sqf
addons/insignia/functions/fnc_getInsignia.sqf
addons/insignia/functions/fnc_setInsignia.sqf
addons/insignia/initSettings.sqf
addons/insignia/script_component.hpp
tools/build.py

- Fix #340 
- Use CBA Setting Changed for insignia application (runs after initialized correctly)
- Make CBA Settings component build correctly with `build.py` as well

Fix Insignia enabled initialization order

---

addons/cba_settings/cba_settings.sqf
addons/main/script_mod.hpp

- Use new setting `noiseScaling` and `fogScaling` (separated from `effectScaling`)
- Leave `fogScaling` at default (`1`) and balance others
**Requires CBA 3.7.0!**

Update NVG settings for ACE 3.12.2

---

addons/mission_autotest/CfgEden.hpp

- Title
```
16:58:53 Error in bin\config.bin/Cfg3DEN/Mission/tac_mission_autotest/AttributeCategories/tac/Attributes/name.condition
16:58:53 Error in bin\config.bin/Cfg3DEN/Mission/tac_mission_autotest/AttributeCategories/tac/Attributes/description.condition
16:58:53 Error in bin\config.bin/Cfg3DEN/Mission/tac_mission_autotest/AttributeCategories/tac/Attributes/gameType.condition
16:58:53 Error in bin\config.bin/Cfg3DEN/Mission/tac_mission_autotest/AttributeCategories/tac/Attributes/author.condition
16:58:53 Error in bin\config.bin/Cfg3DEN/Mission/tac_mission_autotest/AttributeCategories/tac/Attributes/minPlayers.condition
16:58:53 Error in bin\config.bin/Cfg3DEN/Mission/tac_mission_autotest/AttributeCategories/tac/Attributes/maxPlayers.condition …
```

Remove Mission Autotest Eden Attributes conditions (RPT error, unneeded)

---

addons/apollo/initSettings.sqf
addons/armory/initSettings.sqf
addons/bodybag/initSettings.sqf
addons/insignia/initSettings.sqf

- Change to `CBA_fnc_addSetting`
- Mark Apollo settings as needsRestart

Change to CBA_fnc_addSetting and mark Apollo settings as needsRestart

---

addons/cba_settings/cba_settings.sqf

Remove ACRE2 Terrain Loss setting to 0.5 (default since ACRE2 v2.5.0)

---

addons/main/script_mod.hpp
include/x/cba/addons/main/script_macros_common.hpp

- Title
**Merge after https://github.com/CBATeam/CBA_A3/pull/1221 is released!**
TODO:
- With cleaned-up quoting `##`

Use CBA Versioning System properly

---

addons/armory/functions/fnc_dialogControl_amountSelection.sqf

- Use maximum quantity of the item to be stashed by default, instead of `1`.
Quality of life change for faster stashing.

Default to max item stash quantity in Armory

---

addons/armory/XEH_postInitClient.sqf

- Title
Stashing something starts the "full refresh" callback and wait. This would interfere with the Armory UI if the user switched to some other (non-stash) part of the Armory fast enough, causing the displayed list to go blank and requiring a re-open.

Fix Armory full refresh wiping item list

---

AUTHORS.txt
addons/noactions/$PBOPREFIX$
addons/noactions/CfgActions.hpp
addons/noactions/CfgEventHandlers.hpp
addons/noactions/README.md
addons/noactions/XEH_preInit.sqf
addons/noactions/config.cpp
addons/noactions/initSettings.sqf
addons/noactions/script_component.hpp
addons/noactions/stringtable.xml

- Adds a component that allows you to remove certain actions from scroll menu to make it less cluttered.
Removable actions (these usually are bound to some keybinds):
- ~~Eject - Might be useless after next ACE update as commy2 has added same thing. (ACE variant also removes actions added to helos via script)~~
- Rearm
- TurnIn
- TurnOut
- LightOn
- LightOff
None of the actions is disabled by default.
Based on:
https://gitlab.com/armaforces/armaforces_no_actions

Add NoActions component

---

addons/armory/functions/fnc_dialogControl_amountSelection.sqf

- Improve regression from #410
- Retain default 1 when taking items, only set to max when stashing

Default to 1 item take quantity in Armory

---

addons/fatigue/CfgEventHandlers.hpp
addons/fatigue/XEH_postInit.sqf

- Fix missing `XEH_preStart.sqf` file (not needed)
- Not add duty factor on headless clients - Fatigue doesn't run on AI

Fatigue - Fix missing file and ignore on HC

---

optionals/cup_ace_hearing/$PBOPREFIX$
optionals/cup_ace_hearing/CfgWeapons.hpp
optionals/cup_ace_hearing/README.md
optionals/cup_ace_hearing/config.cpp
optionals/cup_ace_hearing/script_component.hpp

- Add ace hearing compatibility to CUP headgear
(Only items with actual headphones were included.)

Add Optional CUP ACE3 Hearing Compatibility

---

addons/apollo/XEH_postInitServer.sqf
addons/apollo/functions/fnc_handleDisconnect.sqf
addons/apollo/functions/fnc_playerSingletonSave.sqf

- Save name given by `HandleDisconnect` (local `profileName` of leaving player) or `profileName` directly on periodic saves.
- Fix empty or AI names being saved.

Fix Apollo name saving

---

addons/cba_settings/cba_settings.sqf

- Fix Medical damage setting (Sum of Trauma & Large hits to vital organs)
- Remove ability to dig ridiculous trenches.
- Increase time to dig the 3 remaining trenches to 60s, 180s & 300s.
- Reduce stamina factor to match increased times.
Note: These settings are being tested via Mission cba_settings until they're at a balanced place.

Fix ACE3 Medical & Balance GRAD Trenches settings

---

optionals/melb_tweaks/$PBOPREFIX$
optionals/melb_tweaks/CfgAmmo.hpp
optionals/melb_tweaks/CfgMagazines.hpp
optionals/melb_tweaks/CfgWeapons.hpp
optionals/melb_tweaks/README.md
optionals/melb_tweaks/config.cpp
optionals/melb_tweaks/script_component.hpp

- Remove gun recoil (`muzzleImpulseFactor`) causing desync/flipping with AFM.
- Revert M134 and GAU-19 tracers to vanilla.
- Revert M134 sound to vanilla.

Add Optional MELB Tweaks

---

addons/armory/dev/test_baseVariants.sqf
addons/armory/functions/fnc_getBaseVariant.sqf

- Title
- Add unit tests for `getBaseVariant` function

Fix Armory combined CBA Scripted Optic and Accessory variant switch

---

addons/cba_settings/cba_settings.sqf

CBA Settings - Refuel hose length from 12m to 20m

---

addons/apollo/functions/fnc_vehicleLoad.sqf
addons/apollo/functions/fnc_vehicleSingletonSave.sqf

Locking:
Not sure how you set this back, but the `locked` command gives a number, so to re-set it use `lock` instead of `setVehicleLock`
Customization:
Vehicle is exported with `BIS_fnc_exportVehicle` and set again with `BIS_fnc_initVehicle`

Apollo - Save vehicle lock state & Customization

---

addons/ratelmarker/XEH_PREP.hpp
addons/ratelmarker/XEH_postInitClient.sqf
addons/ratelmarker/XEH_preInit.sqf
addons/ratelmarker/functions/fnc_createQRM.sqf
addons/ratelmarker/functions/fnc_prepareQRM.sqf
addons/ratelmarker/stringtable.xml

- Add Quick Reference Marker keybind/functionality
Quick Reference Markers (QRMs) allow pilots to quickly make a marker on their MicroDAGR of a point of interest.

Add Quick Reference Marker

---

addons/servers/CfgMainMenuSpotlight.hpp

RPT: 12:15:54 Cannot delete class AoW_Showcase_Future, it is referenced somewhere (used as a base class probably).
`AoW_Showcase_AoW` inherits from `AoW_Showcase_Future` so it can't be deleted first.

Servers - Fix AoW Showcase not being deleted

---

optionals/compat_cup_vehicles/CfgVehicles.hpp

- Wrong inheritance causes UBC.

CUP Vehicles Compat - Fix UBC error

---

addons/cba_settings/cba_settings.sqf

- Can't see any practical use for it other than being a major annoyance.

Settings - Disable weapon cookoff

---

optionals/bnae_falkor_compat_ace/CfgAmmo.hpp
optionals/bnae_falkor_compat_ace/README.md
optionals/bnae_falkor_compat_ace/config.cpp
optionals/bnae_trg42_compat_ace/CfgAmmo.hpp
optionals/bnae_trg42_compat_ace/README.md
optionals/bnae_trg42_compat_ace/config.cpp

- Adds relevant values for ACE ballistics to the TRG42/Falkor Petra.
(Values come from Laid3ack)

Project Infinite - Add ACE ballistic values to 300WM / 338LM

---

addons/apollo/functions/fnc_playerLoadClient.sqf
addons/armory/functions/fnc_dialogControl_populateList.sqf
addons/armory/functions/fnc_getBoxContents.sqf
addons/armory/functions/fnc_subtractData.sqf

- Armory - Fix quantity type for use of `parseSimpleArray`
- Apollo - Delay validation to allow server to sync loadout

Armory - Fix quantity type for use of `parseSimpleArray`

---

extensions/apollo-client/src/lib.rs
extensions/apollo-client/src/main.rs

- Fix crash found by @Lairdd1989 with Armory item descriptions containing non-ASCII whitespaces.
- Replace non-ASCII characters with `[INVALID-CHAR]` so it can be fixed in Armory itself as well.

Extensions - Handle non-ASCII characters gracefully

---

addons/apollo/functions/fnc_vehicleSingletonSave.sqf

- Together with Apollo change (already deployed) only add additional height on spawn if one of the classes, while `Unknown` will be spawned as-is.
This is first change towards better Apollo support for Trenches. However, due to how they work, additional work has to be done (as part of this or separate PRs):
- Spawn trench a bit lower (it's 0.36 too high for some reason) - trenches code probably sets position after spawning? #201 
- Save and set animation state OR we just accept they will all be fully build after server restart #201

Apollo - Add ThingX (PhysX objects) to vehicle classes

---

addons/cba_settings/cba_settings.sqf

- Lowered from 1 to 0.6, might bring back some semblence of sense to AI damage.

CBA Settings - Set AI Damage Threshold to 0.6

---

addons/difficulties/CfgAILevelPresets.hpp
addons/difficulties/CfgAISkill.hpp
addons/difficulties/CfgDifficultyPresets.hpp

- ~~Add Theseus SOG difficulty~~
- ~~SOG AI level (precision = 0.3, skill = 1)~~
- ~~Same Options regarding HUD, markers, killed messages etc.~~
- Set `skillAI` to `1` in Theseus difficulty.
- Adapts SOG's `skillAI` setting, now usable for both without separate difficulties (see below 2 comments).
- Increase maximum Spot Distance and Spot Time to `1`

Difficulties - Set AI skill to 1.0 and allow maximum Spot Distance and Time in Theseus difficulty

---

addons/servers/CfgMainMenuSpotlight.hpp

- Deletes the 3 spotlights that are currently there, tested without running WS and it fails silently, nothing in RPT.

Server - Remove Western Sahara spotlights

---

addons/insurgents/functions/fnc_randomizeGear.sqf
addons/mission/functions/fnc_aar.sqf
addons/mission/functions/fnc_baseSpectator.sqf
addons/mission/functions/fnc_bomber.sqf
addons/mission/functions/fnc_caves.sqf
addons/mission/functions/fnc_collectIntel.sqf
addons/mission/functions/fnc_connectBatteryToDefusable.sqf
addons/mission/functions/fnc_d30Strike.sqf
addons/mission/functions/fnc_forceShooting.sqf
addons/mission/functions/fnc_godMode.sqf
addons/mission/functions/fnc_hunt.sqf
addons/mission/functions/fnc_monitorUnits.sqf
addons/mission/functions/fnc_mortarStrike.sqf
addons/mission/functions/fnc_reaction.sqf
addons/mission/functions/fnc_reinforcements.sqf
addons/mission/functions/fnc_respiratorEffects.sqf
addons/mission/functions/fnc_surrender.sqf
addons/mission/functions/fnc_switchAction.sqf
addons/mission/functions/fnc_teleport.sqf
addons/mission/functions/fnc_toggleLights.sqf
addons/mission/functions/fnc_unconscious.sqf

- Cleanup use of trailing `;` in examples.
- Fix return value documentation for `FUNC(monitorUnits)`.

Mission - Cleanup examples

---

addons/insurgents/functions/fnc_randomizeGear.sqf

- Checks if Simulation is enabled, if not temporarily enable it and disable it again after gear has been applied.

Insurgents - Add compatibility for reinforcements

---

addons/medical/XEH_postInit.sqf

- Log when Fatal Injuries Cardiac Arrest Time modification happens, including full serialized state of the unit's medical.

Medical - Add Fatal Injuries Logging

---

addons/cba_settings/cba_settings.sqf

- Change Allow Repair to Anyone.
Preparation for changes to Engineer role:
> - Basic repair: can repair a vehicle up to 40% with a toolkit (included in basic training).
> - Engineer repair: can repair a vehicle up to 60% with a toolkit in the field (engineer trained).
> - Full repair: with the proper facilities (base or repair vehicle) anyone with a toolkit can fix a vehicle fully.
>
> Toolkit as company-provided asset.

Settings - Change Allow Repair to Anyone

---

addons/mission/functions/fnc_hunt.sqf
addons/mission/functions/fnc_reinforcements.sqf

Noticed some major FPS drops with only the hunt function being ran, deleted groups that were hunting and FPS stabilised.
Data from Alans mission where I noticed the issue ( I skipped 2 hours in-game to get a bunch of groups hunting and have something identical to compare to)
Units active - 67 (approx 50 on hunt)
Hunt was being called from Reinforcements (reinforcements added to mission so it called new hunt)
Original:
Server FPS every check time: 3-14.
Server FPS normal: 90-100.
Rewrite:
Server FPS every check time: 70-77.
Server FPS normal: 90-100.
This actually made a huge difference.
Local benchmarking, (VR mission with player & one group for check):
Original:
- 0.0682 ms
- 0.071 ms
- 0.0704 ms
- 0.072 ms
- 0.071 ms
Rewrite:
- 0.0136 ms
- 0.015 ms
- 0.0138 ms
- 0.0156 ms
- 0.0148 ms

Mission - Optimize Hunt target selection

---

addons/mission/functions/fnc_monitorUnits.sqf

- Removes `playableUnits` from all counters (already has a player counter)
- Separates out checks into variables
- Now does simple numbers instead of array operations (faster)

Mission - Fix players included in Monitor Units AI counting

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_earthquake.sqf

- Rewrite of BIS_fnc_earthquake
- Runs unscheduled, works flawlessly.

Mission - Add Earthquake

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_contaminationGas.sqf
addons/mission/functions/fnc_respiratorEffects.sqf

- Respirator effects now only targets the Head & Torso with burn damage from ACE.
- Now takes an array of markers instead of a singular hardcoded one.
- Uses `_player` param instead of `ACE_player` everywhere.
- Contamination Gas creates visible orange gas within an area. It looks really cool and compliments respirator effects properly.
- Differs from Ground Fog by covering a specific area instead of following you like we did before.

Mission - Rework Respirator Effects and Add Contamination Gas

---

tools/deploy.py

ACE3 has a "new" domain - fixed URL for translation.

Update ACE3 translation guide URL

---

addons/mission/functions/fnc_monitorUnits.sqf

- Currently counts `playableUnits` and subtracts it from all sides where there are no players. No longer does that.
Not overly important as it's mostly used in the editor.

Mission - Fix incorrect Monitor Units counts with players

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_aliveInGroups.sqf
addons/mission/functions/fnc_countAlive.sqf

- Counts alive units in array of groups. Useful for checking remaining AI for reinforcements and such.
Used it [here](https://github.com/Theseus-Aegis/MissionReviews/blob/door-kickers/tac_co_DoorKickers.SefrouRamal/initServer.sqf#L39-L41) for example.

Mission - Add `countAlive` function

---

addons/mission/functions/fnc_switchAction.sqf

Nobody has yet used this in a mission, should be fine to rewrite.
- Used to be handled by a PFH for some unknown reason, now toggles with the ACE Action.
- Has pre-set up based on the initial starting point of the handle either on or off.
- Voltages when on are configurable and the functionality of checking if it's on is the same.
- Optional code condition for action.
- Variable that's set will return bool if it's on or off.

Mission - Rewrite `switchAction`

---

addons/mission/functions/fnc_respiratorEffects.sqf

- Converts mask define to a variable, can be predefined by players beforehand otherwise it'll default to the one in the function.
- Not everyone owns contact, might be useful to be able to add an alternative.
Template:
- Document this.
- Array can be changed at any point.
- Classnames **need** to be lowercase

Mission - Expand Respirator Effects

---

addons/ui_tweaks/Display3DEN.hpp
addons/ui_tweaks/config.cpp

- Been looking to do this for ages, it bothers me that it automatically expands categories in the editor and now it no longer does.

UI Tweaks - Collapse categories by default in Eden

---

optionals/aegis_ace_hearing/$PBOPREFIX$
optionals/aegis_ace_hearing/CfgWeapons.hpp
optionals/aegis_ace_hearing/README.md
optionals/aegis_ace_hearing/config.cpp
optionals/aegis_ace_hearing/script_component.hpp

- Adds ACE hearing properties to helmets that need it.
- Adds `skipWhenMissingDependencies` so we can throw this into main after version 2.14
- Tested and working.

Optionals - Add Aegis ACE Hearing

---

addons/mission/functions/fnc_respiratorEffects.sqf

- Overlay didn't get removed on death, this should fix that.
- Added optional ability to disable breathing sounds (manual input required)

Mission - Add death failsafe and optional method of disabling sounds to `respiratorEffects`

---

addons/mission/functions/fnc_setSleeping.sqf

- Moves local check into the wakeup.
- Everything else should be global for animations to apply.

Mission - Fix `setSleeping` function

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_downloadIntel.sqf

- Laptop which can have intel downloaded from it.
- Uses procedural textures to show total filesize and what percentage the download is currently at. Also shows a progress bar like this: `[=====]` (at 50%)
- Ran from per frame handler where the refresh time is done by downloadTime / 10 (download is done in 10 ticks)
- Laptop, Rugged Laptop and PC Set - Screen are supported.
- Texture Source is supported as a param.
- ~~Memory usage is randomised on each tick~~.
- Code now displays with delays to be fancy and simulate typing.
- Day/Time of last use is now randomised.
- Linux heresy is more accurate.
- Initial texture on use moved from ACE action to PFH.
To Do:

Mission - Add Download Intel function

---

optionals/bnae_rk95_compat_ace/CfgWeapons.hpp

- Title
How nobody fixed this in 5+ years is beyond me, but it was really simple, just completely wrong inheritance... Looks like it was copied from TRG42, but there rail stuff is added to the base class, here it's to a sub-class only (base is non-rail model).

Optional Project Infinite RK95 - Fix Rail UBC

---

addons/apollo/XEH_postInitServer.sqf
addons/apollo/initSettings.sqf
addons/apollo/stringtable.xml

- Close #402 
- Call Apollo to reset server data (map/mission) under conditions defined below, if **Apollo is enabled** and **"Allow Server Reset" is enabled**.
- Add a setting "Allow Server Reset" (default enabled) which could be turned off to force keep the same data. While this is disabled, map/mission data will also not be saved.
Apollo follows the following logic:
```
if players and vehicles disabled
-> [no reset]
else
(get saved map/mission)
if mission starts with "tac_ca_"
cut mission name to "tac_ca_CampaignName"
if map and mission didn't change
-> [no reset]
else
if players enabled
-> [reset player positions]
if vehicles enabled
-> [delete saved vehicles]
(save current map/mission)
```
_Theoretically this is implemented so we can keep track …

Apollo - Add Automatic Server Reset

---

addons/apollo/functions/fnc_playerLoadClient.sqf
addons/apollo/functions/fnc_playerSingletonSave.sqf

- Remove sending `inVehicle` and `alive` to backend - have been removed from database a while ago.
- Select last selected weapon on player load.
**Requires Apollo (`cleanup` branch) and Athena (`reselect-weapon`) updates!**

Apollo - Reselect weapon and cleanup unused variables

---

addons/apollo/functions/fnc_playerSingletonSave.sqf

- Title
Might happen on mission switch, where HandleDisconnect seems to run too late and no UIDs can be retrieved anymore.
Added a check in Apollo as well for double safety.

Apollo - Fix trying to save player with invalid UID

---

addons/mission/functions/fnc_reinforcements.sqf

- If a non-existing group is passed RPT will be flooded with:
```
private _playerList = [] >
17:01:32   Error leader: Type Array, expected Object,Group,Team member
17:01:32 File x\tac\addons\mission\functions\fnc_reinforcements.sqf..., line 28
17:01:32 Error in expression <r) exitWith {};
private _groupLeader = leader _group;
private _playerList = [] >
17:01:32   Error position: <leader _group;
```
Instead, group is now default `grpNull` and will exit with a warning for it.

Mission - Handle invalid groups gracefully

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_markBuildings.sqf

- Adds a function to mark buildings the same way the map objects are done. (See image on VR)
- It's not exactly fast depending on how many objects are in the array, but wouldn't be noticeable on mission start.
Marker name has to be unique, only thing I could think of that makes it so is using the object position. Examples:
```
"2293.223775.22-4.76837e-007"
"2329.533795.150"
"2373.953806.670"
"2330.523794.51-0.00336075"
"2356.343912.850"
"2343.283912.930"
"2330.373912.780"
"2317.313912.870"
"2304.33912.80"
```

Mission - Add Mark Buildings Function

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_ambientCarAlarm.sqf
addons/mission/functions/fnc_carAlarm.sqf

- Adds an ambient styled car alarm when car is hit.
- Runs locally per player with global variable to stop it from running after it should be removed.
Works now far as I can tell.

Mission - Add Car Alarm function

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_players.sqf

- Adds an alternative to `CBA_fnc_players`, will filter out spectators and optionally filter out pilots.
Tested, working.

Mission - Add Players function

---

addons/mission/functions/fnc_reinforcements.sqf

**Requires (#675)**
- Rework Reinforcements to take array instead of singular group.
- Removes Hunt integration.
- Sets default state to true.
Tested, working. (Including BWC for old method)

Mission - Rework Reinforcements

---

addons/mission/functions/fnc_mortarStrike.sqf

- Lowers the complexity of the function, removes the barrages part entirely.
- Still handles MK6 Mortar & D30 as before.
- random amount is now whole number.
- Handles invalid markers with error. (has to be done before inRange otherwise that will be the error, easier to debug this way.)
- Instead of firing an amount every X barrage, now just fires 1 round until it reaches required amount.
- Returns the ETA of the round and the amount fired.
- Now uses the correct syntax for `doArtilleryFire`
**I'm being nice and even writing out a reason for this one before I forget.**
Something was off with amount & barrages, not entirely sure what but you wouldn't get the amount fired you wanted. Plus it just added to the confusion of this entire function.
I had a …

Mission - Rework Mortar Strike

---

addons/headless/$PBOPREFIX$
addons/headless/CfgEventHandlers.hpp
addons/headless/XEH_PREP.hpp
addons/headless/XEH_preInit.sqf
addons/headless/XEH_preStart.sqf
addons/headless/config.cpp
addons/headless/functions/fnc_moveHeadless.sqf
addons/headless/initSettings.inc.sqf
addons/headless/script_component.hpp
addons/headless/stringtable.xml
addons/mission/functions/fnc_players.sqf

- Adds new headless component.
- Setting for disabling function.
- HC is hidden to prevent clipping issues (Still functions as normal)
- Runs a loop every 60s to select a random player not in spectator or flying and sets the HC position to them.
- Can be disabled/re-enabled in mission.

Add Headless automatic move with players

---

addons/mission/functions/fnc_ping.sqf

- `maxSize` wasn't passed to the PFH, wouldn't ever delete itself.

Mission - Fix Ping function never getting deleted

---

addons/mission/XEH_postInit.sqf
addons/mission/functions/fnc_mortarStrike.sqf

- Currently the mortar can completely skip firing the first round because of traversal time. This should get it to look in the right direction before the `doArtilleryFire` begins giving it a much better chance of actually firing instead of skipping.
- My initial testing of this is done in a function that calls this one, it works as intended.
- Testing it by setting direction just before it fires isn't enough time, but even if the strike fails for any reason having it face the right way doesn't matter all that much.

Mission - Fix mortar firing delay

---

addons/cba_settings/cba_settings.sqf

- Reverted the 0.6 AI damage, shouldn't be necessary anymore.
**Trench Stuff:**
Me and Mick have been balancing out trenches trying to move us away from digging sandcastles everywhere we go.
- Removed the largest
- Readded the smallest
- Set the times to be 2 minutes, 4 minutes & 8 minutes, obviously scales down with amount of players helping.
**Repair Stuff:**
Coordinated with Mick & Alan
- Sets up a reasonable full repair timer, nearly 7 minutes for a vehicle at 50% is insane.
- Lowers the wheel patching from 70% to 50% otherwise spare wheels are only useful for direct replacement of a destroyed one.

Settings - Adjust AI Damage Threshold, Repair and Trench

---

addons/mission/functions/fnc_reaction.sqf

- Removes "ALL" as an option.
- Types is now an array
- Added Combat type, re-enables PATH/MOVE on AI entering combat mode.
- BWC support for old syntax.
Seen enough missions checking for what the combat feature does, may aswell include it.

Mission - Rework Reaction and Add Combat Mode

---

addons/debug_console/XEH_PREP.hpp
addons/debug_console/XEH_postInit.sqf
addons/debug_console/functions/fnc_addCurator.sqf
addons/debug_console/functions/fnc_handleRespawn.sqf

- Improves editable objects selection, now includes vehicles while remaining performant.
- Handles respawn as dying breaks the original curator assignment.
_Needs testing._

Debug Console - Include vehicles in editable objects and Fix respawn curator assignment

---

addons/melb/functions/fnc_toggleMFD.sqf

- title, `animateSource` is apparently better optimised for MP and more efficient.

MELB - Switch `animate` to `animateSource`

---

addons/mission/XEH_PREP.hpp
addons/mission/functions/fnc_chemicalDetector.sqf

- Pretty simple, more immersion than anything, has geiger sounds and a threat level you can monitor.
- It plays nice with respiratorEffects and contaminationGas.

Mission - Add Chemical Detector function

---

addons/difficulties/XEH_postInit.sqf
addons/difficulties/functions/fnc_setUnitAccuracy.sqf

- Includes RPG units with the accuracy factor changes
- Aiming shake is also affected (without it RPGs are still pinpoint accurate, shouldn't do anything to vehicles really.)

Difficulties - Include RPG Units in Accuracy Factor

---

addons/medical/XEH_PREP.hpp
addons/medical/XEH_postInit.sqf
addons/medical/XEH_preInit.sqf
addons/medical/config.cpp
addons/medical/functions/fnc_unconsciousFX.sqf
addons/medical/initSettings.inc.sqf
addons/medical/script_component.hpp
addons/medical/stringtable.xml

- Adds a screaming sound when you get knocked unconscious
- Percentage of making a groaning sound while you're unconscious (if you have a heart rate above 40, this excludes CPR)
- Uses sounds from ACE.
- Has a chance setting and a timer setting.
- 50% by default.
- 30s by default. 
- The groaning check is done locally on the unconscious person, ~~uses the `say3D` event from mission (why its now a requirement)~~.
- PFH is removed when awake, so if you die it goes away.
- Requested by El Presidente.

Medical - Add Unconscious Effects

---

addons/debug_console/functions/fnc_handleRespawn.sqf

- Respawn doesn't reassign curator module because arguments are in the wrong place.

Debug Console - Fix curator reassignment (backwards logic)

---

addons/mission/RscGUI.hpp
addons/mission/XEH_PREP.hpp
addons/mission/config.cpp
addons/mission/functions/fnc_keypadPress.sqf
addons/mission/functions/fnc_keypadSetup.sqf
addons/mission/script_component.hpp

- Keypad GUI stuff, allows for multiple to be used at the same time.

Mission - Add Keypad functionality
