Theseus-Aegis/Mods

- addons/ratelmarker/XEH_postInitClient.sqf
> Canged keybinds to common TAC category

- addons/ratelmarker/CfgVehicles.hpp
> Removed spawn from create RATEL marker menu

- addons/air_security/README.md
- addons/air_security/config.cpp
- addons/air_security/functions/fnc_canSecure.sqf
- addons/air_security/functions/fnc_canUnsecure.sqf
- addons/air_security/functions/fnc_setSecurity.sqf
- addons/main/config.cpp
> Cleaned Up Air Security

- addons/ratelmarker/functions/fnc_createMarker.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
- addons/ratelmarker/stringtable.xml
> Used ACE3 Hint in RATEL Marker

- addons/air_security/CfgEventHandlers.hpp
- addons/air_security/XEH_postInitClient.sqf
- addons/air_security/stringtable.xml
- addons/ratelmarker/XEH_postInitClient.sqf
> Added keybind to Air Security

-  .travis.yml
- tools/ace3permissions.txt
- tools/build.py
- tools/deploy.py
- tools/make.py
- tools/search_unused_privates.py
- tools/setup.py
- tools/sqf_validator.py
- tools/stringtablediag.py
- tools/stringtableduplicates.py
> Travis CI and Tools

- tools/sqf_validator.py
> Use a forward slash in path for travis to work properly
> Revert the backslash in SQF validator

- AUTHORS.txt
- addons/air_security/stringtable.xml
- addons/common/stringtable.xml
- addons/heavylifter/stringtable.xml
- addons/radios/stringtable.xml
- addons/ratelmarker/stringtable.xml
> Add Spanish Translations

- addons/radios/CfgSounds.hpp
- addons/radios/functions/fnc_addRadioTrackActions.sqf
- addons/radios/functions/fnc_getRadioTracks.sqf
- addons/radios/stringtable.xml
> Change track interaction menu text to be parsed from config

- addons/common/stringtable.xml
> Add forgotten TAC Mod Team Spanish stringtable

- addons/ratelmarker/functions/fnc_canUseMarkerMenu.sqf
> Fix RATEL Marker showing for passengers

- addons/armory/CfgVehicles.hpp
- addons/armory/config.cpp
- addons/armory/stringtable.xml
> Add Armory Locker Zeus compatibility

- addons/armory/CfgEventHandlers.hpp
- addons/armory/CfgVehicles.hpp
- addons/armory/Dialog.hpp
- addons/armory/XEH_postInitServer.sqf
- addons/armory/XEH_preInit.sqf
- addons/armory/functions/fnc_canAddArmory.sqf
- addons/armory/functions/fnc_canOpenArmory.sqf
- addons/armory/functions/fnc_closeArmory.sqf
- addons/armory/functions/fnc_dialogControl_back.sqf
- addons/armory/functions/fnc_getBoxContents.sqf
- addons/armory/functions/fnc_init.sqf
- addons/armory/functions/fnc_openArmory.sqf
- addons/armory/functions/fnc_sendData.sqf
> Prevent multiple people using same Armory Locker

- addons/armory/XEH_preInit.sqf
- addons/armory/functions/fnc_containsItems.sqf
- addons/armory/functions/fnc_dialogControl_populateList.sqf
- addons/armory/functions/fnc_sendData.sqf
Also fixed backpacks not listing, bug from #78
> Stash Failsafes

- addons/air_security/stringtable.xml
- addons/armory/stringtable.xml
- addons/common/stringtable.xml
- addons/heavylifter/stringtable.xml
- addons/radios/stringtable.xml
- addons/ratelmarker/stringtable.xml
Added all strings for the german version. Some names might be too long,
please check.
> Added german translations

- addons/armory/XEH_postInitServer.sqf
- addons/armory/functions/fnc_canAddArmory.sqf
- addons/armory/functions/fnc_closeArmory.sqf
- addons/armory/functions/fnc_containsItems.sqf
- addons/armory/functions/fnc_dialogControl_amountSelection.sqf
- addons/armory/functions/fnc_dialogControl_list.sqf
- addons/armory/functions/fnc_dialogControl_populateList.sqf
- addons/armory/functions/fnc_extractSubCategories.sqf
- addons/armory/functions/fnc_getBoxContents.sqf
- addons/armory/functions/fnc_getDataVanilla.sqf
- addons/armory/functions/fnc_init.sqf
- addons/armory/functions/fnc_moduleInit.sqf
- addons/armory/functions/fnc_sendData.sqf
- addons/armory/functions/fnc_subtractData.sqf
- addons/radios/functions/fnc_addRadioTrackActions.sqf
- addons/ratelmarker/functions/fnc_canUseMarkerMenu.sqf
> Local to Private conversion

- addons/armory/Dialog.hpp
- addons/armory/functions/fnc_dialogControl_back.sqf
- addons/armory/functions/fnc_getDataVanilla.sqf
- addons/armory/functions/fnc_openArmory.sqf
> Fix Armory UI scaling on different resolutions

- optionals/tban_armed/CfgVehicles.hpp
> Removed redundant Taliban Fighters Armed dependency fixes

- addons/armory/stringtable.xml
- addons/zeus/stringtable.xml
Added german Zeus translations and fixed a typo in the old ones.
> German translations for Zeus

- addons/shootingrange/stringtable.xml
From #100 by @System98  to proper branch.
> Shooting range german

- optionals/tban_armed/config.cpp
> Fix Taliban Fighters Armed dependency

- addons/radios/CfgEventHandlers.hpp
- addons/radios/CfgSounds.hpp
- addons/radios/CfgVehicles.hpp
- addons/radios/XEH_PREP.hpp
- addons/radios/functions/fnc_canPlayRadio.sqf
- addons/radios/functions/fnc_canStopRadio.sqf
- addons/radios/functions/fnc_changeVolume.sqf
- addons/radios/functions/fnc_getRadioTracks.sqf
- addons/radios/functions/fnc_playRadio.sqf
- addons/radios/stringtable.xml
> Repurpose radios to be in-vehicle radios

- addons/ratelmarker/functions/fnc_createMarker.sqf
- addons/ratelmarker/functions/fnc_createMarkerMenu.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
- Add proper headers to functions in RATEL Marker component
- Use `private` command in RATEL Marker component
> Use private command in RATEL Marker, Update headers

- extras/blank/CfgEventHandlers.hpp
- extras/blank/README.md
- extras/blank/XEH_PREP.hpp
- extras/blank/XEH_preStart.sqf
- extras/blank/config.cpp
- extras/blank/functions/fnc_empty.sqf
- extras/blank/script_component.hpp
- Update `blank` component in extras to use new things
> Blank component update

- addons/ratelmarker/functions/fnc_createMarker.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
- addons/ratelmarker/markerMenu.hpp
- addons/ratelmarker/script_component.hpp
- Fixes #136 
- Enhances marker preparation by using `getMapPosFromGrid` function from ACE3
- Cleanups marker menu config by passing the control directly
> Fix ratel marker coords

- addons/main/CfgSettings.hpp
- addons/main/config.cpp
- addons/main/script_mod.hpp
- addons/zeus/config.cpp
- Added CBA Versioning for ACE3
- Moved ace_zeus dependency to tac_zeus
- Closes #140
> Add CBA Versioning for ACE3

- addons/difficulties/$PBOPREFIX$
- addons/difficulties/CfgDifficultyPresets.hpp
- addons/difficulties/README.md
- addons/difficulties/config.cpp
- addons/difficulties/script_component.hpp
- Adds `Theseus` difficulty with settings like no-longer-working ACE3's Elite difficulty
- Necessary after Arma 3 1.58 and its Difficulty Overhaul
> Add Theseus difficulty

- addons/heavylifter/CfgVehicles.hpp
- Fix #145 
- Disable ACE3 interactions on Heavy Lifter helper object
> Disable Heavy Lifter ACE3 interactions

- addons/zeus/CfgVehicles.hpp
- Fixes #144 
- Hides base Zeus module
- Fixed indentation
> Hide base zeus module

- addons/radios/CfgVehicles.hpp
- addons/radios/functions/fnc_canPlayRadio.sqf
- Closes #143 
- Adds radio playing support to static radio objects
- Removes redundant `canPlayRadio` condition in sub-action
> Add static radio object support

- addons/armory/XEH_PREP.hpp
- addons/armory/functions/fnc_addArmoryItems.sqf
- addons/armory/functions/fnc_addItems.sqf
- addons/armory/functions/fnc_getDataVanilla.sqf
- addons/armory/functions/fnc_init.sqf
- addons/armory/functions/fnc_openArmory.sqf
- addons/armory/functions/fnc_sendData.sqf
- addons/armory/functions/fnc_subtractData.sqf
- Adds framework for scripted adding of gear to Armory box using Vanilla system
- Work on #84
> Add framework for Vanilla gear

- addons/shootingrange/functions/fnc_create.sqf
- addons/shootingrange/functions/fnc_moduleInit.sqf
- addons/shootingrange/functions/fnc_popupPFH.sqf
- Fixes #154 
- Finishes rampage mode when all targets are hit as well, in addition to time limit.
- Fixes #153
> Fix shooting range

- addons/shootingrange/functions/fnc_checkConfig.sqf
- Fix pause duration showing in modes where it shouldn't - fix #165
- Fix Rampage mode being displayed as Trigger
- Improves check config function
> Fix config check output

- addons/air_security/CfgVehicles.hpp
- addons/air_security/functions/fnc_setSecurity.sqf
- addons/armory/CfgVehicles.hpp
- addons/armory/Dialog.hpp
- addons/armory/functions/fnc_dialogControl.sqf
- addons/armory/functions/fnc_dialogControl_back.sqf
- addons/armory/functions/fnc_dialogControl_list.sqf
- addons/armory/functions/fnc_dialogControl_main.sqf
- addons/armory/functions/fnc_dialogControl_takestash.sqf
- addons/headless/CfgVehicles.hpp
- addons/heavylifter/CfgVehicles.hpp
- addons/heavylifter/functions/fnc_prepare.sqf
- addons/heavylifter/functions/fnc_unprepare.sqf
- addons/insignia/CfgUnitInsignia.hpp
- addons/main/config.cpp
- addons/radios/CfgSounds.hpp
- addons/radios/CfgVehicles.hpp
- addons/ratelmarker/CfgVehicles.hpp
- addons/ratelmarker/functions/fnc_createMarker.sqf
- addons/shootingrange/CfgVehicles.hpp
- addons/zeus/CfgVehicles.hpp
> Use new QPATHTOF CBA macro

- addons/armory/functions/fnc_dialogControl_populateList.sqf
- addons/armory/functions/fnc_sendData.sqf
- addons/bodybag/functions/fnc_moveInventory.sqf
- addons/bodybag/functions/fnc_placeDroppedWeapons.sqf
- addons/headless/functions/fnc_rebalance.sqf
- addons/radios/CfgEventHandlers.hpp
- addons/radios/XEH_postInitClient.sqf
- addons/radios/functions/fnc_playRadio.sqf
- addons/ratelmarker/CfgVehicles.hpp
- addons/shootingrange/CfgEventHandlers.hpp
- addons/shootingrange/XEH_postInitClient.sqf
- addons/shootingrange/functions/fnc_animateTarget.sqf
- addons/shootingrange/functions/fnc_playSoundSignal.sqf
- addons/shootingrange/functions/fnc_start.sqf
- Use new functions from CBA 2.4.0:
- Delayed execution
- Config getters
- Binocular magazine management
- Replace deprecated `CBA_fnc_globalSay3d` with custom event using `say3D` command
- Replace deprecated `CBA_fnc_removeXCargoGlobal` with `CBA_fnc_removeXCargo`
> Use new CBA 2.4.0 functions

- addons/air_security/XEH_postInitClient.sqf
- addons/air_security/functions/fnc_setSecurity.sqf
- addons/headless/XEH_postInit.sqf
- addons/headless/XEH_preInit.sqf
- addons/ratelmarker/XEH_postInitClient.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
- addons/zeus/XEH_postInitServer.sqf
- addons/zeus/functions/fnc_moduleAddObjectToChronosLocal.sqf
- Convert ACE3 events to CBA events where possible
- Others will follow after ACE 3.6.0 releases with CBA events as well.
> Convert events to CBA events framework

- addons/shootingrange/functions/fnc_setTargetGroups.sqf
- Fix #169 
- Fix script error on shooting range trigger mode when no invalid targets are set
> Fix shooting range trigger mode script error

- addons/radios/functions/fnc_getRadioTracks.sqf
> Improve getRadioTracks config reading

- addons/armory/functions/fnc_dialogControl_populateList.sqf
- addons/armory/functions/fnc_extractSubCategories.sqf
- addons/armory/functions/fnc_isCompatible.sqf
> Fix isCompatible not checking magazines

- addons/air_security/functions/fnc_setSecurity.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
> Fix inverted targetEvent parameters

- addons/shootingrange/functions/fnc_handleHitPart.sqf
- addons/shootingrange/functions/fnc_popupPFH.sqf
> Prevent same target from popping up twice in a row

- addons/shootingrange/functions/fnc_create.sqf
- addons/shootingrange/functions/fnc_moduleInit.sqf
- addons/shootingrange/stringtable.xml
- Add range name to RPT logging
- Add lowest countdown time value to module tooltip
> Improve RPT logging in Shooting Range

- addons/armory/stringtable.xml
- addons/bodybag/stringtable.xml
- addons/radios/stringtable.xml
- addons/shootingrange/stringtable.xml
Add missing german translations to Armory, Bodybag, Radios and
Shootingrange
> Add german translations

- addons/headless/functions/fnc_handleConnectHC.sqf
- addons/headless/functions/fnc_handleDisconnect.sqf
- addons/headless/functions/fnc_handleInitPost.sqf
- addons/headless/functions/fnc_rebalance.sqf
* Fix errors in headless function headers
> Fix error in functions header

- addons/shootingrange/functions/fnc_handleHitPart.sqf
- Title
- Ref. https://github.com/Theseus-Aegis/Olympus/pull/53
> Fix shooting range stayDown variable not respected when nopop is undefined

- addons/armory/CfgEden.hpp
- addons/armory/CfgEventHandlers.hpp
- addons/armory/CfgVehicles.hpp
- addons/armory/XEH_postInitClient.sqf
- addons/armory/config.cpp
- addons/armory/functions/fnc_init.sqf
- addons/armory/functions/fnc_moduleInit.sqf
- addons/main/CfgEden.hpp
- addons/main/CfgModuleCategories.hpp
- addons/main/CfgVehicleClasses.hpp
- addons/main/config.cpp
- addons/main/stringtable.xml
- Add Armory Eden attribute
- Remove module setting for objects
> Add Armory Eden attribute

- addons/apollo/XEH_postInitClient.sqf
- addons/apollo/functions/fnc_handleConnect.sqf
- addons/apollo/functions/fnc_handleDisconnect.sqf
- addons/apollo/functions/fnc_playerLoadClient.sqf
- addons/apollo/functions/fnc_playerSaveClient.sqf
- addons/apollo/functions/fnc_playerSingletonSave.sqf
- addons/insignia/XEH_preInit.sqf
- addons/insignia/functions/fnc_getInsignia.sqf
- addons/insignia/functions/fnc_setInsignia.sqf
- Use player variable for insignia tracking.
- Shorten variable name in Apollo save.
- Prevent saving until `lastSavedTime` is defined after loading.
- Fix position and direction failing due to simulation toggling (no need to do that anyways).
- More debug logging.
> Insignia and Apollo save improvements, Fix loading 

- optionals/tban_armed/CfgVehicles.hpp
- optionals/tban_uniforms_allsides/$PBOPREFIX$
- optionals/tban_uniforms_allsides/CfgVehicles.hpp
- optionals/tban_uniforms_allsides/README.md
- optionals/tban_uniforms_allsides/config.cpp
- optionals/tban_uniforms_allsides/script_component.hpp
- Allow uniforms from Taliban Fighters mod to be usable by all sides.
- Convert tabs to spaces in TBan Armed component.
All vanilla and other mods used by Theseus Inc. will be changed in ACE3 to also allow this by https://github.com/acemod/ACE3/pull/4435.
> Allow Taliban Fighters uniforms for all sides

- addons/air_security/config.cpp
- addons/air_security/script_component.hpp
- addons/apollo/config.cpp
- addons/apollo/script_component.hpp
- addons/armory/config.cpp
- addons/armory/script_component.hpp
- addons/bodybag/config.cpp
- addons/bodybag/script_component.hpp
- addons/difficulties/config.cpp
- addons/difficulties/script_component.hpp
- addons/heavylifter/config.cpp
- addons/heavylifter/script_component.hpp
- addons/insignia/config.cpp
- addons/insignia/script_component.hpp
- addons/main/config.cpp
- addons/main/script_component.hpp
- addons/main/script_mod.hpp
- addons/misc/config.cpp
- addons/misc/script_component.hpp
- addons/radios/config.cpp
- addons/radios/script_component.hpp
- addons/ratelmarker/config.cpp
- addons/ratelmarker/script_component.hpp
- addons/resources/config.cpp
- addons/resources/script_component.hpp
- addons/shootingrange/config.cpp
- addons/shootingrange/script_component.hpp
- addons/zeus/config.cpp
- addons/zeus/script_component.hpp
- Title
- Set required ACE3 version to 3.8.0
> Add beautified component names

- addons/apollo/XEH_postInitClient.sqf
- addons/armory/functions/fnc_getDataChronos.sqf
- addons/main/script_mod.hpp
- Title
- Set required CBA version to 3.1.1
> Use ERROR_MSG where applicable

- README.md
- extras/blank/config.cpp
- extras/blank/script_component.hpp
- Update extras component with beautified component name
- Update `make.py` arguments in README.md
> Update extras component and make.py release build note

- addons/ballistics/$PBOPREFIX$
- addons/ballistics/CfgAmmo.hpp
- addons/ballistics/README.md
- addons/ballistics/config.cpp
- addons/ballistics/script_component.hpp
- Add ballistics component
- Fix 40mm smoke shell bouncing excessively
> Fix 40mm smoke shell bouncing excessively

- addons/ratelmarker/CfgVehicles.hpp
> Allow RATEL Marker usage in Planes

- addons/heavylifter/CfgEventHandlers.hpp
- addons/heavylifter/CfgVehicles.hpp
- addons/heavylifter/XEH_postInit.sqf
- addons/heavylifter/functions/fnc_prepare.sqf
- addons/heavylifter/functions/fnc_unprepare.sqf
- addons/heavylifter/script_component.hpp
- optionals/compat_cha_av8b/CfgVehicles.hpp
- optionals/compat_melb/$PBOPREFIX$
- optionals/compat_melb/CfgVehicles.hpp
- optionals/compat_melb/README.md
- optionals/compat_melb/config.cpp
- optionals/compat_melb/script_component.hpp
- optionals/compat_rhsafrf/CfgVehicles.hpp
- optionals/compat_rhsusf/CfgVehicles.hpp
- Close #234 
- Add MELB Heavy Lifter Compatibility
- Add 3d debug/position checker function
- Lowercase `AttachPos[]` config entry
- Use ACE3 status effect `"blockDamage"` - fixes locality
- Fix floating after detaching hooks
- Add instant attaching macro for debug
> Add MELB Heavy Lifter Compatibility

- addons/shootingrange/functions/fnc_create.sqf
- addons/shootingrange/stringtable.xml
- Close #233 
- Add support for pre-made triggers in Shooting Range
- Change trigger creation/parsing to only create/set one trigger per group (optimization)
> Add support for pre-made triggers in Shooting Range

- addons/air_security/functions/fnc_setSecurity.sqf
- addons/apollo/functions/fnc_handleKilled.sqf
- addons/apollo/functions/fnc_moduleInit.sqf
- addons/armory/CfgVehicles.hpp
- addons/armory/functions/fnc_containsItems.sqf
- addons/armory/functions/fnc_getDataChronos.sqf
- addons/armory/functions/fnc_init.sqf
- addons/armory/functions/fnc_moduleInit.sqf
- addons/armory/functions/fnc_processAction.sqf
- addons/heavylifter/functions/fnc_prepare.sqf
- addons/heavylifter/functions/fnc_progress.sqf
- addons/heavylifter/functions/fnc_unprepare.sqf
- addons/main/script_macros.hpp
- addons/mission_autotest/functions/fnc_testApollo.sqf
- addons/radios/functions/fnc_addRadioTrackActions.sqf
- addons/radios/functions/fnc_playRadio.sqf
- addons/ratelmarker/functions/fnc_createMarker.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
- addons/shootingrange/functions/fnc_addConfigCountdownTimes.sqf
- addons/shootingrange/functions/fnc_addConfigDurations.sqf
- addons/shootingrange/functions/fnc_addConfigPauseDurations.sqf
- addons/shootingrange/functions/fnc_addConfigTargetAmounts.sqf
- addons/shootingrange/functions/fnc_checkConfig.sqf
- addons/shootingrange/functions/fnc_create.sqf
- addons/shootingrange/functions/fnc_handleHitPart.sqf
- addons/shootingrange/functions/fnc_moduleInit.sqf
- addons/shootingrange/functions/fnc_notifyVicinity.sqf
- addons/shootingrange/functions/fnc_start.sqf
- addons/shootingrange/functions/fnc_stop.sqf
- addons/zeus/functions/fnc_moduleAddObjectToChronosLocal.sqf
- Add ACE3 `GVAR` and `FUNC` reference macros
- Mass replace ACE3 functions and global variables with ACE3 reference macros
> Use ACE3 reference macros

- addons/armory/functions/fnc_dialogControl_populateList.sqf
- addons/armory/functions/fnc_openArmory.sqf
> Throw unknown class error as pop-up in Armory

- addons/apollo/functions/fnc_playerLoadClient.sqf
- addons/armory/functions/fnc_getDataChronos.sqf
> Exit instantly if error returned from ApolloClient "get"

- addons/heavylifter/CfgVehicles.hpp
- addons/heavylifter/XEH_PREP.hpp
- addons/heavylifter/XEH_postInit.sqf
- addons/heavylifter/functions/fnc_exportConfig.sqf
- addons/heavylifter/script_component.hpp
- Close #259
- Add weight restriction (mass < 20000)
- Add config export function
- Add support for Apex vehicles
- Add support for `Motorcycle` and `Ship_F` vehicles (possibly included in exported config)
Todo:
> Add heavy lifter config export function and Apex support

- addons/ratelmarker/functions/fnc_canUseMarkerMenu.sqf
- addons/ratelmarker/functions/fnc_createMarkerMenu.sqf
- addons/ratelmarker/markerMenu.hpp
> Fix marker menu CTD when opening when already open

- addons/settings/$PBOPREFIX$
- addons/settings/CfgEventHandlers.hpp
- addons/settings/XEH_preInit.sqf
- addons/settings/cba/settings.sqf
- addons/settings/config.cpp
- addons/settings/script_component.hpp
> Add static CBA Settings component

- optionals/melb_ace_fastroping/CfgVehicles.hpp
> Use RHS MELB ACE3 Fastroping rope positions

- addons/armory/functions/fnc_containsItems.sqf
- addons/armory/functions/fnc_processAction.sqf
- addons/armory/stringtable.xml
> Prevent stashing if other weapons/containers in box are not empty

- addons/apollo/XEH_postInitClient.sqf
- addons/apollo/functions/fnc_handleDisconnect.sqf
- addons/apollo/functions/fnc_playerSaveClient.sqf
- addons/apollo/functions/fnc_playerSingletonSave.sqf
- Title
- Remove redundant is object hidden check
> Fix disconnect saving when it shouldn't

- addons/apollo/XEH_postInitClient.sqf
- addons/apollo/functions/fnc_handleDisconnect.sqf
- addons/apollo/functions/fnc_playerLoadClient.sqf
- addons/apollo/functions/fnc_playerSaveClient.sqf
- addons/apollo/functions/fnc_playerSingletonSave.sqf
- Fix onDisconnect saving - introduced in dev
- Remove current stance saving - requires Apollo update
> Apollo Fixes

- addons/apollo/functions/fnc_playerSingletonSave.sqf
> Fix ACRE replacement Apollo script error

- addons/apollo/functions/fnc_playerSingletonSave.sqf
> Fix goggles saving (bandaid for vanilla bug)

- optionals/compat_cup_vehicles/CfgVehicles.hpp
- optionals/compat_cup_vehicles/config.cpp
- optionals/cup_units_nouniformrestrictions/CfgVehicles.hpp
- Update `cup_units_nouniformrestrictions` for CUP 1.9.0
- Update `cup_compat_vehicles` for CUP 1.9.0
> Update definitions for CUP 1.9.0

- addons/apollo/functions/fnc_playerSingletonSave.sqf
- Properly fix #282 
- Fix issue in #285
> Fix ACRE radio replacement type condition

- addons/apollo/functions/fnc_playerLoadClient.sqf
- addons/apollo/functions/fnc_playerSingletonSave.sqf
> Properly fix goggles saving (bandaid for vanilla bug)

- addons/mission_autotest/functions/fnc_testDebugConsole.sqf
- addons/mission_autotest/stringtable.xml
- Title
- Improve shown text
Array value is for specific user IDs + admin with debug console access.
> Fix Mission Autotest for 1.72 array value

- addons/cba_settings/cba_settings.sqf
> Disable NIArms Magazine Switch

- addons/armory/functions/fnc_processAction.sqf
- Work on #280 
- Use `select` instead of `if-then-else`
> Force retrieve box contents when stashing

- addons/armory/functions/fnc_isCompatible.sqf
> Check GL magazines for compatible ammo in Amory

- addons/misc/functions/fnc_toggleAlarm.sqf
- addons/ratelmarker/functions/fnc_prepareMarker.sqf
- addons/shootingrange/functions/fnc_popupPFH.sqf
- addons/shootingrange/functions/fnc_start.sqf
- addons/shootingrange/functions/fnc_stop.sqf
- Fix [SQF Linter](https://github.com/LordGolias/sqf) warnings
> SQFLinter Cleanup

- addons/shootingrange/XEH_PREP.hpp
- addons/shootingrange/XEH_postInit.sqf
- addons/shootingrange/functions/fnc_notifyVicinity.sqf
- addons/shootingrange/functions/fnc_start.sqf
- addons/shootingrange/functions/fnc_stop.sqf
- addons/shootingrange/functions/fnc_textsIntoLocalizedString.sqf
> Use client localization in Shooting Range

- addons/apollo/functions/fnc_lockerAction.sqf
- addons/armory/XEH_PREP.hpp
- addons/armory/XEH_postInitClient.sqf
- addons/armory/functions/fnc_openArmory.sqf
- addons/armory/functions/fnc_processAction.sqf
- addons/armory/functions/fnc_updateData.sqf
- Close #305 
- Fix stashing duplicating (will first subtract data, then force update when server is done)
> Make force retrieving box contents network-friendly

- addons/bodybag/functions/fnc_moveInventory.sqf
- addons/bodybag/functions/fnc_saveDroppedWeapons.sqf
- Fix #314 
- Fix same for pistol when pistol is equipped
- Improve handling of preset classes (not important to us, but in case anyone else is using this)
> Fix attachments never getting considered for bodybag move

- addons/air_security/README.md
- addons/air_security/functions/fnc_canSecure.sqf
- addons/air_security/functions/fnc_canUnsecure.sqf
- addons/air_security/functions/fnc_setSecurity.sqf
> Only allow Unsecuring if Secured by Air Security

- addons/heavylifter/functions/fnc_canAttach.sqf
- addons/heavylifter/functions/fnc_canDetach.sqf
- addons/heavylifter/functions/fnc_prepare.sqf
- addons/heavylifter/functions/fnc_progress.sqf
- addons/heavylifter/functions/fnc_unprepare.sqf
- Cleanup examples (no more semi-colons)
- Remove disabled engine requirement (using ACE3's "blockEngine" status effect)
- Remove unlocked vehicle requirement (all work is done outside, so why should it be unlocked)
- Allow crew inside
- Use `QUOTE(ADDON)` for ACE3 status effects
> Cleanup and Improve Heavy Lifter

- addons/mission_autotest/CfgEden.hpp
- addons/mission_autotest/XEH_PREP.hpp
- addons/mission_autotest/functions/fnc_testTargetDebug.sqf
- addons/mission_autotest/stringtable.xml
> Add CBA Target Debug to Mission Autotest

- addons/cba_settings/cba_settings.sqf
- addons/main/script_mod.hpp
- Only default to server settings (mission previously always overwrote it if not forced, now it works properly)
**Requires CBA 3.5.0!**
> Unforce CBA Settings (3.5.0 defaults to server properly)

- addons/apollo/XEH_postInitServer.sqf
- addons/cba_settings/cba_settings.sqf
- addons/mission_autotest/functions/fnc_testApollo.sqf
> Replace ACE Settings references to CBA Settings

- README.md
- extensions/src/common/constants.h
- tools/deploy.py
- Fix repository name in all files referencing it
- Fix `vcproj` folder name for x64 extensions
Should make badges and links work properly again.
> Fix repo name

- addons/cba_settings/cba_settings.sqf
> Use proper type for ACE3 Medical AI Enabled For setting

- addons/cba_settings/cba_settings.sqf
> Disable ACE3 Name Tags Ranks by default

- .travis.yml
> Update Python in Travis to 3.6 (new default)

- addons/cba_settings/cba_settings.sqf
- Remove ignoreAntennaDirection setting.
> Removed ignoreAntennaDirection

- addons/cba_settings/cba_settings.sqf
- Add ace_map_defaultChannel setting (moved from MissionTemplate)
> Added ace_map_defaultChannel setting

- addons/cba_settings/cba_settings.sqf
- Add the custom NVG values to cba_settings
> Add NVG settings

- addons/difficulties/CfgSurfaces.hpp
- addons/difficulties/config.cpp
Adds CfgSurfaces - AIAvoidStance to Difficulties, which helps prevent AI from going prone at the most weird locations.
> Add AIAvoidStance to difficulties

- addons/air_security/stringtable.xml
- addons/apollo/stringtable.xml
- addons/armory/stringtable.xml
- addons/bodybag/stringtable.xml
- addons/heavylifter/stringtable.xml
- addons/insignia/stringtable.xml
- addons/main/stringtable.xml
- addons/mission_autotest/stringtable.xml
- addons/radios/stringtable.xml
- addons/ratelmarker/stringtable.xml
- addons/zeus/stringtable.xml
- I didn't do the shooting range because I don't have the setup to test it.
we got german translations, why not french? :D
> Add french translations for all modules except shooting range

- tools/config_style_checker.py
- tools/sqf_validator.py
- Update keywords list
- Change line number index (start from 1 instead of 0)
- https://github.com/CBATeam/CBA_A3/pull/1043
> Update SQF Validator (more keywords, # select)

- addons/slingload/$PBOPREFIX$
- addons/slingload/CfgEventHandlers.hpp
- addons/slingload/README.md
- addons/slingload/XEH_postInitServer.sqf
- addons/slingload/XEH_preInit.sqf
- addons/slingload/config.cpp
- addons/slingload/script_component.hpp
> Add Sling-Load locality improvement

- addons/apollo/functions/fnc_lockerAction.sqf
- addons/armory/functions/fnc_dialogControl_populateList.sqf
- addons/radios/functions/fnc_canStopRadio.sqf
- addons/radios/functions/fnc_playRadio.sqf
- addons/shootingrange/functions/fnc_addConfigCountdownTimes.sqf
- addons/shootingrange/functions/fnc_addConfigDurations.sqf
- addons/shootingrange/functions/fnc_addConfigPauseDurations.sqf
- addons/shootingrange/functions/fnc_addConfigTargetAmounts.sqf
- addons/shootingrange/functions/fnc_checkConfig.sqf
- addons/shootingrange/functions/fnc_handleHitPart.sqf
- addons/shootingrange/functions/fnc_moduleInit.sqf
- addons/zeus/functions/fnc_moduleAddObjectToChronosLocal.sqf
- Cleanup unused privates
- Lower-case `Unused` -> `unused`
> Cleanup unused privates

- addons/armory/functions/fnc_isCompatible.sqf
- Close #381 
- Support (sub-)muzzle magazines (eg. GL) in Armory
- Optimize Armory `fnc_isCompatible`
> Use CBA_fnc_compatibleMagazines in Armory

- addons/armory/XEH_PREP.hpp
- addons/armory/functions/fnc_getBaseVariant.sqf
- addons/armory/functions/fnc_processAction.sqf
- addons/armory/script_component.hpp
> Switch scripted optics and accessories to base variants on Armory Stash

- addons/cba_settings/cba_settings.sqf
> Add ZEN disable live search (Zeus 'Enter' to search)

- addons/apollo/functions/fnc_lockerAction.sqf
- addons/armory/functions/fnc_processAction.sqf
- Title
This backend is pretty shit, it literally sends a command backwards using local variables, so we need to keep this one.
> Fix Armory connection with Apollo backend

- addons/cba_settings/cba_settings.sqf
- Disabled the gear animation when using Zeus
> Add ZEN Disable Gear Animations setting

- addons/cba_settings/cba_settings.sqf
> Add ACE3 Advanced Ballistics Enabled setting

- addons/shootingrange/functions/fnc_handleHitPart.sqf
- addons/shootingrange/functions/fnc_popupPFH.sqf
- addons/shootingrange/functions/fnc_popupPFHexit.sqf
- addons/shootingrange/functions/fnc_start.sqf
- Title - `sqflint` complained.
> Use non-command variable name for Shooting Range score

- .github/workflows/arma.yml
- .travis.yml
- addons/air_security/stringtable.xml
- addons/apollo/stringtable.xml
- addons/armory/stringtable.xml
- addons/bodybag/stringtable.xml
- addons/cba_settings/cba_settings.sqf
- addons/heavylifter/stringtable.xml
- addons/insignia/stringtable.xml
- addons/main/stringtable.xml
- addons/medical/stringtable.xml
- addons/mission_autotest/stringtable.xml
> Add Arma CI Workflow (validate, lint, build)

- addons/apollo/functions/fnc_lockerAction.sqf
- addons/armory/functions/fnc_getBaseVariant.sqf
- addons/armory/functions/fnc_processAction.sqf
- Tile
- Fix removal (duplication) of accessories
**Requires update of Apollo!**
> Switch disposable launchers to base variant on Armory stash

- addons/heavylifter/CfgVehicles.hpp
- optionals/compat_cup_vehicles/CfgVehicles.hpp
- Update Heavy Lifter definitions for vanilla 1.96
- Update CUP Heavy Lifter definitions for CUP 1.13.0 - closes #409
> Update Heavy Lifter definitions for Arma 3 1.96 and CUP 1.13.0

- addons/noactions/CfgActions.hpp
- addons/noactions/README.md
- addons/noactions/initSettings.sqf
- addons/noactions/stringtable.xml
- Fix setting descriptions
- Remote No-Rearm setting (already removed by ace)
> Fix No Actions descriptions and Remove No Rearm

- addons/cba_settings/cba_settings.sqf
- Add Clear Trauma After Bandage ACE3 Medical Setting
- Increase Cardiac Arrest Time to 5 min
- Fix Fatal Injuries Player setting name (not being applied)
> Improve ACE3 Medical Rewrite Settings

- addons/fatigue/$PBOPREFIX$
- addons/fatigue/CfgEventHandlers.hpp
- addons/fatigue/README.md
- addons/fatigue/XEH_postInitClient.sqf
- addons/fatigue/config.cpp
- addons/fatigue/script_component.hpp
> Add Fatigue modifications (crouch-walking made harder)

- addons/cba_settings/cba_settings.sqf
> Increase Spontaneous Wake-Up Chance to 30%

- addons/shootingrange/README.md
- addons/shootingrange/functions/fnc_stop.sqf
> Add Shooting Range Stopped event

- addons/noactions/CfgActions.hpp
> No Actions - Fix `LightOff` inheritance

- addons/apollo/functions/fnc_playerLoadClient.sqf
- addons/apollo/functions/fnc_playerSaveClient.sqf
- Title
CBA 3.14.0 added third parameter to player events, overwriting our default.
> Apollo - Fix saving on loadout change (CBA 3.14.0)

- addons/medical/ACE_Medical_Actions.hpp
- Previously just as effective as Morphine with virtually no downside. Now they do significantly less pain relief, affect HR and last slightly longer in system.
> Medical - Balance Painkillers for Rewrite

- addons/cba_settings/cba_settings.sqf
> Settings - Fix ACE3 Medical Wounds Reopening

- addons/cba_settings/cba_settings.sqf
> Settings - Add ACE3 Medical Fatal Damage Source

- addons/cba_settings/cba_settings.sqf
- Updates the optional mod to the newer standalone version.
> Update Blastcore to updated Standalone in Check PBOs Whitelist

- addons/apollo/functions/fnc_playerSingletonSave.sqf
- Close #435 - included
- Work on #201 - Earplugs support (not in the intended way, but will do temporarily)
> Add Earplugs to Apollo and use new ACRE2 filter unit loadout API

- addons/shootingrange/functions/fnc_start.sqf
- Fix https://github.com/Theseus-Aegis/Olympus/issues/123
> Fix Shooting Range accuracy tracking

- addons/bodybag/CfgVehicles.hpp
> Make Bodybags Carryable

- addons/apollo/XEH_postInitServer.sqf
- addons/apollo/functions/fnc_playerLoadClient.sqf
- addons/apollo/functions/fnc_playerSaveClient.sqf
> Fix Apollo name saving server profile name instead of client

- optionals/cup_ace_hearing/CfgWeapons.hpp
- Removed the culprit and it's inheritants.
> CUP ACE3 Hearing - Fix updating base class

- addons/insurgents/README.md
> Add example Insurgents gear mission config

- addons/fatigue/XEH_postInit.sqf
- Title
Thanks to @Flyzoor for the find.
> Fix fatigue duty increase in crouch-walk

- optionals/tban_armed/script_component.hpp
- Fix quoting (HEMTT warnings).
> TBAN Armed - Fix quoting

- addons/insurgents/CfgVehicles.hpp
- Remove restrictions from Insurgent Uniforms
> Insurgents - Remove Side Restrictions From Uniforms

- optionals/compat_cup_vehicles/CfgVehicles.hpp
- optionals/compat_cup_vehicles/config.cpp
-  Update Heavy Lifter definitions for CUP 1.15.0
> Update Heavy Lifter definitions for CUP 1.15.0

- addons/insurgents/CfgVehicles.hpp
- addons/insurgents/config.cpp
- addons/insurgents/stringtable.xml
- Added African insurgent for Independent
- Added Middle Eastern insurgent for Opfor
> Expand Random Insurgents

- addons/supplies/CfgVehicles.hpp
- optionals/compat_cup_weapons/CfgVehicles.hpp
- optionals/compat_cup_weapons/config.cpp
- CUP Weapons Compat was missing M136 Launcher.
- Added more rockets to Launchers box.
- Increased capacity of Launcher box.
> Expand Supplies & CUP Compat

- optionals/compat_cup_weapons/CfgVehicles.hpp
- Fixed missing inheritance class
> CUP Weapons Compat - Fix Missing Inheritance Class

- addons/cba_settings/cba_settings.sqf
- Lowered NV noise from `5` to `3`.
- Allowed the option of bodybagging while unit is unconscious.
> CBA Settings - Update Night Vision and Bodybag Settings

- addons/cba_settings/cba_settings.sqf
Reverts Theseus-Aegis/Mods#471
Default was good and as we want it...
> CBA Settings - Revert Bodybag setting

- addons/ui_tweaks/$PBOPREFIX$
- addons/ui_tweaks/README.md
- addons/ui_tweaks/RscDisplay.hpp
- addons/ui_tweaks/config.cpp
- addons/ui_tweaks/script_component.hpp
[Before](https://i.gyazo.com/6f62a43476925f168f44c65fb17a161a.jpg)
[After](https://i.gyazo.com/42432c7bce7e74fb4200d20a64337c5b.jpg)
> Add UI Tweaks Component

- addons/cba_settings/cba_settings.sqf
> CBA Settings - Require Engineer to repair vehicles

- addons/cba_settings/cba_settings.sqf
- title
Temporary measure until a different solution is found.
> CBA Settings - Require cardiac arrest for death

- addons/difficulties/CfgDifficultyPresets.hpp
> Difficulties - Disable Group Commands

- addons/servers/CfgMainMenuSpotlight.hpp
> Servers - Remove Art of War from Main Menu Spotlight

- addons/bodybag/XEH_PREP.hpp
- addons/bodybag/functions/fnc_createBodybagBackup.sqf
- addons/bodybag/functions/fnc_getBodybagContents.sqf
- Add a function to get bodybag contents
- Add a function to create a new bodybag with contents from getter function
> Bodybag - Add backup API functions

- addons/cba_settings/cba_settings.sqf
- Allows Dragging & Firing
- Sets Death chance to 15%
- Pain unconscious chance to 20%
> CBA Settings - Set ACE3 Drag and Fire, Death Chance and Pain Unconscious Chance

- addons/cba_settings/cba_settings.sqf
> CBA Settings - Change fuel hose length to 30 from 20

- addons/supplies/CfgEventHandlers.hpp
- addons/supplies/XEH_PREP.hpp
- addons/supplies/XEH_postInitClient.sqf
- addons/supplies/XEH_postInitServer.sqf
- addons/supplies/XEH_preInit.sqf
- addons/supplies/functions/fnc_medicalArsenal.sqf
- addons/supplies/functions/fnc_traitActions.sqf
- addons/supplies/stringtable.xml
- Add interactions to get traits for medic and engineer.
ToDo:
> Supplies - Trait interactions and mission trait persistence

- addons/supplies/CfgWeapons.hpp
- addons/supplies/XEH_postInitClient.sqf
- addons/supplies/config.cpp
- addons/supplies/stringtable.xml
> Supplies - Add randomized box functionality

- addons/heavylifter/CfgVehicles.hpp
- Fixes refuel action showing on the helper object.
> Heavy Lifter - Remove refuel actions from helper

- addons/cba_settings/cba_settings.sqf
> CBA Settings - Add OCAP to PBO Check Whitelist

- addons/apollo/XEH_postInitClient.sqf
- addons/apollo/functions/fnc_playerSingletonSave.sqf
- addons/apollo/script_component.hpp
- Title - see comments in code
- Add more debug to possibly catch rare loadout load failure
> Apollo - Attempt to fix load positioning error

- addons/apollo/XEH_postInitServer.sqf
- addons/apollo/functions/fnc_invokeJavaMethod.sqf
- Add support for `jni-rs` server extension (supporting Apollo on Linux).
> Apollo - Convert JNI extension calls to `arma-rs` supported format

- addons/armory/README.md
- addons/armory/functions/fnc_subtractData.sqf
> Armory - Fix quantity type error on take action

- addons/heavylifter/functions/fnc_exportConfig.sqf
> Heavy Lifter - Remove redundant select

- extensions/apollo-client/src/lib.rs
> Extensions - Update API endpoint

- addons/servers/CfgMainMenuSpotlight.hpp
- As title states, change the IP address to the new server.
Closes #524
> Servers - Change IP address

- addons/insurgents/CfgVehicles.hpp
- addons/insurgents/XEH_preInit.sqf
- addons/insurgents/functions/fnc_randomizeGear.sqf
- addons/insurgents/initSettings.sqf
- addons/insurgents/script_component.hpp
- addons/insurgents/stringtable.xml
- Changes all static chances to configurable settings.
Supersedes #526
> Insurgents - Change static chances to settings

- extensions/Cargo.lock
- extensions/apollo-client/Cargo.toml
- extensions/apollo-client/src/lib.rs
- extensions/apollo-client/src/main.rs
- Update dependencies and log trace in binary
- [Switch to reusable `reqwest::blocking::Client`
> Apollo Client - Handle request error gracefully and optimize

- addons/cba_settings/cba_settings.sqf
- addons/medical/CfgEventHandlers.hpp
- addons/medical/XEH_postInit.sqf
- addons/medical/XEH_postInitClient.sqf
- addons/medical/XEH_preInit.sqf
- addons/medical/config.cpp
- addons/medical/initSettings.sqf
- addons/medical/stringtable.xml
- Add a Coefficient (CBA setting) for controlling the Cardiac Arrest Time on fatal injuries when `Fatal Injuries` is NOT `Always`.
**Example:**
- `Fatal Injuries Player` set to `In Cardiac Arrest`
- `Fatal Injuries Cardiac Arrest Time Coefficient` set to `0.2`
- Player gets fatal injury, they go to Cardiac Arrest (as per `Fatal Injuries Player`)
- Player also gets `Cardiac Arrest Time` modified by a factor of `0.2` (by default: `300 * 0.2 = 60`)
- **Result: 60 seconds Cardiac Arrest Time on fatal injury**
**Notes:**
- Player doesn't get fatal injury: everything happens as before
- Player gets multiple fatal injuries within 1 second: coefficient will only be applied once
- Player gets out of cardiac arrest, but stays unconscious, and falls back into …
> Medical - Add Fatal Injuries Cardiac Arrest Time Coefficient

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_jam.sqf
- Add jamming script (see header)
Needs testing (simplified from Jack's version into single-function with parameters) and verification that parameters are applied properly. Probably also sane examples.
Moved from https://github.com/Theseus-Aegis/MissionTemplate/pull/43.
> Mission - Add jamming script

- addons/mission/functions/fnc_jam.sqf
> Mission - Fix Jam script ACRE2 mod check

- addons/mission/XEH_postInit.sqf
> Mission - Move mission type verification to template

- addons/mission/functions/fnc_aar.sqf
- Fix unknown variable `_missionType`. In Template it was valid from upper scope.
> Mission - Fix Auto-AAR

- optionals/ws_nouniformrestrictions/$PBOPREFIX$
- optionals/ws_nouniformrestrictions/CfgVehicles.hpp
- optionals/ws_nouniformrestrictions/README.md
- optionals/ws_nouniformrestrictions/config.cpp
- optionals/ws_nouniformrestrictions/script_component.hpp
> Optionals - Add Western Sahara No Uniform Restriction

- addons/apollo/functions/fnc_vehicleSingletonSave.sqf
> Apollo - Fix vehicle saving (invalid class passed to extension)

- addons/mission/functions/fnc_surrender.sqf
- Lowers chance to 5 by default
- Adds distance check (default: 400)
- Adds Rally chance (default: 0)
> Mission - Add Rallying to Surrender

- addons/mission/functions/fnc_bomber.sqf
> Mission - Optimize Bomber target selection

- addons/mission/functions/fnc_teleport.sqf
- Adds support for paths for custom icons.
> Mission - Add support for custom icons in Teleport

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_groundFog.sqf
- Adds the original (slightly reworked) ground fog Kresky used a few times.
- Now has a condition to stop it.
- Customisable fog colours!
~~Need to test properly.~~
> Mission - Add Ground Fog

- addons/mission/functions/fnc_groundFog.sqf
> Mission - Fix Groundfog condition check

- addons/mission/functions/fnc_bomber.sqf
- Didn't see it from the copy/paste.
> Mission - Fix Bomber target checking

- addons/medical/stringtable.xml
> Medical - Fix stringtable entries

- addons/mission/functions/fnc_contaminationGas.sqf
- Returns particle emitters created for gas clearance.
- Configurable gas size 0-3
- Longer lasting clouds
> Mission - Return particle emitters in Contamination Gas

- addons/difficulties/functions/fnc_setUnitAccuracy.sqf
- addons/mission/functions/fnc_dialogue.sqf
> Difficulties / Mission - Fix Typos

- addons/mission/functions/fnc_respiratorEffects.sqf
- Ability to customise how much damage per tick and the actual tick rate of damage.
> Mission - Add Damage Per Tick and Damage Tick Rate to Respirator Effects

- optionals/aegis_nouniformrestrictions/$PBOPREFIX$
- optionals/aegis_nouniformrestrictions/CfgVehicles.hpp
- optionals/aegis_nouniformrestrictions/README.md
- optionals/aegis_nouniformrestrictions/config.cpp
- optionals/aegis_nouniformrestrictions/script_component.hpp
> Optionals - Add Aegis No Uniform Restrictions

- extensions/Cargo.lock
- Update extension dependencies
> Extensions - Update dependencies

- addons/servers/CfgMainMenuSpotlight.hpp
- title
- Was doing it for AF mods so I thought I could make a PR for you too <3
> Servers - Remove S.O.G. Prairie Fire and Spearhead 1944 from Main Menu Spotlight

- addons/mission/functions/fnc_mortarStrike.sqf
- Switched from defines to private variables.
> Mission - Add D30 functionality to Mortar Strike

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_setSleeping.sqf
- addons/mission/functions/fnc_sleeping.sqf
- Puts AI into a "sleeping" animation loop.
- Alternative call wakes them up, it can be staggered or immediate.
- Handles locality automatically.
> Mission - Add AI Sleeping function

- addons/insurgents/XEH_preInit.sqf
- addons/insurgents/script_component.hpp
- Title
Thanks to https://github.com/ArmaForces/Mods/pull/157!
> Insurgents - Use HashMap instead of Namespace

- addons/performance/$PBOPREFIX$
- addons/performance/CfgEventHandlers.hpp
- addons/performance/README.md
- addons/performance/XEH_preInit.sqf
- addons/performance/config.cpp
- addons/performance/initSettings.sqf
- addons/performance/script_component.hpp
- addons/performance/stringtable.xml
- Title
Integrated from https://github.com/ArmaForces/Mods/tree/1edfc790b025f3aa4203def1a6f364c0c529b9d5/addons/remotesensors thanks to @veteran29!
> Add performance setting to Disable Remote Sensors on Clients

- addons/flags/$PBOPREFIX$
- addons/flags/CfgVehicles.hpp
- addons/flags/README.md
- addons/flags/config.cpp
- addons/flags/script_component.hpp
- Title
Integrated from https://github.com/ArmaForces/Mods/tree/1edfc790b025f3aa4203def1a6f364c0c529b9d5/addons/flags thanks to @3Mydlo3!
> Add vanilla country markers to flag poles

- addons/mission/XEH_PREP.hpp
- addons/mission/XEH_postInit.sqf
- addons/mission/XEH_preInit.sqf
- addons/mission/functions/fnc_assignNVG.sqf
- addons/mission/functions/fnc_assignNVGpfh.sqf
- Temporarily until ACE release.
- No settings.
> Mission - Add automatic AI NVG assignment

- addons/mission/functions/fnc_downloadIntel.sqf
> Mission - Add Icon to download intel function

- addons/cba_settings/cba_settings.sqf
> Settings - Disable NIArms Grip Switch model replacing

- addons/acre/config.cpp
- addons/breaching/config.cpp
- addons/cup/config.cpp
- addons/insurgents/config.cpp
- addons/milgp/config.cpp
- addons/ui_tweaks/config.cpp
> Various - Cleanup `requiredAddons`

- addons/mission/functions/fnc_godMode.sqf
- Allow easier communication from admins to only spectating players (eg. reinforcements or logistics).
> Mission - Add Spectators God Mode group

- addons/radios/XEH_postInitClient.sqf
- addons/radios/functions/fnc_stop.sqf
- Should fix the source not being deleted for everybody.
> Radios - Fix stop working only for player stopping it

- addons/mission/XEH_PREP.hpp
- addons/mission/XEH_postInit.sqf
- addons/mission/functions/fnc_ping.sqf
- Ping an object location, customisable colour & max size (capped at 120)
https://github.com/Theseus-Aegis/Mods/assets/29175040/8b85b514-3e1d-41a1-ba2c-e067a5fa0ae9
> Mission - Add Ping function

- addons/insurgents/script_component.hpp
- addons/mission/script_component.hpp
- Fix macro redefinitions (HEMTT v1.9.0 warnings)
- Add missing beautified component names
> General - Fix macro redefinitions and add missing beautified component names

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_debugTriggerArea.sqf
- addons/mission/functions/fnc_triggerArea.sqf
- Gets all triggers, makes a marker for them for visual clarity.
- Should've made this years ago.
> Mission - Add Trigger Area debug function

- addons/medical/CfgWeapons.hpp
> Medical - Fix missing ACE strings

- addons/mission/functions/fnc_dialogue.sqf
- title
- It's fade in time, not on screen time.
> Mission - Fix incorrect parameter in Dialogue

- addons/bodybag/functions/fnc_createBodybagBackup.sqf
> Bodybag - Fix bodybag backup using wrong bodybag object

- addons/radios/functions/fnc_init.sqf
- addons/shootingrange/functions/fnc_checkConfig.sqf
- Fix commas which should be semi-colons thanks to HEMTT @BrettMayson
> General - Fix commas which should be semi-colons

- addons/mission/functions/fnc_monitorUnits.sqf
- title, variable is only ever changed on server and it should be used on server watch field anyway.
- Var was added in (#654)
> Mission - Add Hunt groups to monitor units

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_lockDoors.sqf
- Adds Door Locking (and unlocking, but the naming is hard so it's `lockDoors`)
- Can be done locally per player or globally.
> Mission - Add Door Lock function

- addons/bodybag/ACE_Medical_Treatment_Actions.hpp
- addons/bodybag/stringtable.xml
- addons/supplies/functions/fnc_medicalArsenal.sqf
- After next ACE release bodybags will use separated entries with names for bodybagging.
**Requires ACE3 v3.16.2!**
> Bodybag - Separate action for Orange bodybag

- addons/cba_settings/cba_settings.sqf
- addons/main/script_mod.hpp
- Remove setting that is now default in **ACE3 v3.16.2**.
**Requires ACE3 v3.16.2!**
> Settings - Remove Fatal Damage Source

- addons/supplies/functions/fnc_medicalArsenal.sqf
- Doesn't need to be added globally as function already happens per client anyway.
> Supplies - Fix Medical Arsenal adding virtual items globally

- addons/mission/XEH_preInit.sqf
- addons/mission/functions/fnc_monitorUnits.sqf
- When calling `monitorUnits` locally it shows `scalar` instead of a count, it bothers me so now it's fixed.
- Also moves FPS to first case because it fits properly.
> Mission - Fix Hunt Group not showing count

- addons/mission/functions/fnc_groundFog.sqf
- It's faster and more reliable.
> Mission - Better vehicle check for ground fog

- addons/mission/functions/fnc_disableAI.sqf
- addons/mission/functions/fnc_enableAI.sqf
> Mission - Allow units in disableAI / enableAI functions

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_blacklistHC.sqf
- addons/mission/functions/fnc_blacklistHeadless.sqf
- Covers both groups and units, mostly for checks in functions that require the HC blacklist.
> Mission - Add Headless Blacklist wrapper function

- addons/headless/functions/fnc_moveHeadless.sqf
> Headless - Improve position by taking average and removing outliers

- addons/mission/XEH_postInit.sqf
- addons/mission/functions/fnc_bomber.sqf
- addons/mission/functions/fnc_hunt.sqf
- addons/mission/functions/fnc_mortarStrike.sqf
- addons/mission/functions/fnc_ping.sqf
- addons/mission/functions/fnc_respiratorEffects.sqf
**Requires (#675)**
- Converts all AL/EG commands to events and utilises targetEvent where necessary.
- respiratorEffects now has optional 3rd param (see attached images) and utilises 2.16 cutRsc `drawOverHud` param. (draw under)
- Bomber & Hunt now use new players function.
- Alters Hunt function; Increases refresh rate to 10 by default, removes `setGroupOwner`
- Fixes Bomber function; removed `setGroupOwner`, moved `setSpeedMode` to after `doMove` call, removed the delay on exploding after unconscious.
**Testing:**
- Tested bomber on the server
- Tested respiratorEffects on the server
- Hunt uses the same logic as Bomber, should work.
<details>
<summary>Images</summary>
Without additional effect.
With.
</details>
> Mission - Alter and fix functions

- addons/cba_settings/cba_settings.sqf
- Raise performance factor because it might be a bit too low.
- Raise weight factor to be more beneficial to lighter loadouts.
> CBA Settings - Alter fatigue settings

- addons/apollo/functions/fnc_vehicleLoad.sqf
> Apollo - Fix vehicles taking drop damage after spawn

- addons/headless/initSettings.inc.sqf
> Headless - Fix Setting Error

- addons/supplies/functions/fnc_medicalArsenal.sqf
- Still using old painkiller classname.
> Supplies - Fix medical arsenal using old painkiller class

- addons/melb/CfgMagazines.hpp
- All rockets have muzzleImpulseFactor inheriting from this one magazine.
> MELB - Fix AFM recoil from rocket weapons

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_soundSource.sqf
- Essentially a fancy wrapper for `createSoundSource`, returns the sound source or you can have it delete automatically after X seconds.
- Checks if sound exists from main config or mission config.
> Mission - Add Sound Source function

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_battlefieldMemorial.sqf
- Editor object is not global, any attributes do not set on the server. Did this in my campaign to make it work.
> Mission - Add Battlefield Memorial Function

- addons/mission/XEH_postInit.sqf
- addons/mission/functions/fnc_bomber.sqf
- Sick of this function.
- AI stand in place, won't do anything and I think it's combat mode doing it.
> Mission - Fix Bomber function combat behaviour

- addons/mission/functions/fnc_battlefieldMemorial.sqf
- I may have accidentally pushed the wrong version, not my tested and working one.
> Mission - Fix Battlefield Memorial

- addons/mission/functions/fnc_countAlive.sqf
- addons/mission/functions/fnc_debugTriggerArea.sqf
- addons/mission/functions/fnc_disableAI.sqf
- addons/mission/functions/fnc_enableAI.sqf
- addons/mission/functions/fnc_markBuildings.sqf
- addons/mission/functions/fnc_mortarStrike.sqf
- addons/mission/functions/fnc_reaction.sqf
- addons/mission/functions/fnc_reinforcementWaves.sqf
- addons/mission/functions/fnc_reinforcements.sqf
- addons/mission/functions/fnc_setSleeping.sqf
- addons/mission/functions/fnc_surrender.sqf
- addons/mission/functions/fnc_toggleLights.sqf
- isServer checks for server only functions
- Run more expensive debug checks only in 3DEN.
- Reinforcements distance check only runs if its being called > 0, check becomes expensive with 20 players and it increases with distance.
- Global functions (designed to run Server || HC) exit early if hasInterface outside of 3DEN.
- Reaction has new param for removing events after use, except combat that always gets removed.
> Mission - General improvements and optimizations

- addons/servers/CfgMainMenuSpotlight.hpp
> Servers - Remove Reaction Forces main menu spotlight

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_degradedVehicle.sqf
- Rewrite of the original used in a campaign a few years back, makes vehicles a nightmare to use.
> Mission - Add Degraded Vehicle function

- addons/mission_autotest/CfgEden.hpp
- Utilises inheritance for the entries in Cfg3DEN.
> Mission Autotest - Utilise inheritance for `Cfg3DEN`

- addons/difficulties/CfgAILevelPresets.hpp
- addons/difficulties/CfgDifficultyPresets.hpp
- title
- We should've done this ages ago
> Difficulty - Add Theseus SOG difficulty

- addons/apollo/functions/fnc_getPlayerInfo.sqf
- addons/breaching/functions/fnc_breach.sqf
- addons/mission/functions/fnc_monitorUnits.sqf
- addons/mission/functions/fnc_reinforcements.sqf
- addons/mission/functions/fnc_surrender.sqf
- addons/ratelmarker/functions/fnc_createQRM.sqf
- addons/ratelmarker/functions/fnc_prepareQRM.sqf
- Stops hemtt complaining about it.
> All - Fix command casing

- addons/cba_settings/cba_settings.sqf
- Changes we wanted when you were redoing yours.
Requires ACE 3.18.0 or RC due to Frag rewrite. We can finally use spalling it seems.
> CBA Settings - Setting updates

- addons/mission/XEH_postInit.sqf
- addons/mission/functions/fnc_dialogueLocal.sqf
- New diary subject to log all the dialogue messages that come across so they aren't lost.
- Tested locally, worked just fine.
- Diary entry title is done via what time it happened, easiest way to track it and what order they happened in.
- People keep asking for this.
> Mission - Add Diary entry for dialogue

- addons/armory/functions/fnc_getBaseVariant.sqf
- CBA updated to hashmaps.
- we did not.
> Armory - Fix getVariable on Hashmap

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_vehicleSpawner.sqf
- Base function used by the mission template, simplified variant of the Olympus one.
Should be merged and released with (https://github.com/Theseus-Aegis/MissionTemplate/pull/107)
> Mission - Add Vehicle Spawner

- addons/apollo/stringtable.xml
- addons/armory/stringtable.xml
- addons/bodybag/stringtable.xml
- addons/difficulties/stringtable.xml
- addons/gimmick/stringtable.xml
- addons/insurgents/stringtable.xml
- addons/main/stringtable.xml
- addons/mission_autotest/stringtable.xml
- addons/noactions/stringtable.xml
- addons/radios/stringtable.xml
- addons/ratelmarker/stringtable.xml
- addons/servers/stringtable.xml
- addons/shootingrange/stringtable.xml
- addons/supplies/stringtable.xml
- addons/zeus/stringtable.xml
- Uses `hemtt ln sort`
- Doesn't include medical component because of #716 (did it there)
> All - Sort Stringtables

- addons/apollo/functions/fnc_playerSingletonSave.sqf
- addons/armory/functions/fnc_getBaseVariant.sqf
- addons/bodybag/functions/fnc_moveInventory.sqf
- addons/insurgents/XEH_preInit.sqf
- addons/insurgents/functions/fnc_randomizeGear.sqf
- addons/ratelmarker/functions/fnc_prepareQRM.sqf
- addons/shootingrange/functions/fnc_configure.sqf
- addons/shootingrange/functions/fnc_create.sqf
- addons/zeus/functions/fnc_moduleAddObjectToChronosLocal.sqf
- Alters all of the "unneeded nots", mostly switching to `isNotEqualTo`
> All - HEMTT Suggestions

- addons/mission/XEH_PREP.hpp
- addons/mission/functions/fnc_ambientEffects.sqf
> Mission - Add Ambient Effects function

- addons/ratelmarker/markerMenu.hpp
> General - Apply suggestions from HEMTT 1.14.7

- addons/mission/Cfg3DEN.hpp
- addons/mission/CfgEditorCategories.hpp
- addons/mission/XEH_PREP.hpp
- addons/mission/compositions/contract_helios/composition.sqe
- addons/mission/compositions/contract_helios/header.sqe
- addons/mission/compositions/contract_template/composition.sqe
- addons/mission/compositions/contract_template/header.sqe
- addons/mission/compositions/extra_arcadian_black/composition.sqe
- addons/mission/compositions/extra_arcadian_black/header.sqe
- addons/mission/compositions/extra_arcadian_green/composition.sqe
- addons/mission/compositions/extra_arcadian_green/header.sqe
- addons/mission/compositions/extra_arcadian_tan/composition.sqe
- addons/mission/compositions/extra_arcadian_tan/header.sqe
- addons/mission/compositions/sog_full_arsenal/composition.sqe
- addons/mission/compositions/sog_full_arsenal/header.sqe
- addons/mission/compositions/sog_template/composition.sqe
- addons/mission/compositions/sog_template/header.sqe
- addons/mission/compositions/sog_zeus/composition.sqe
- addons/mission/compositions/sog_zeus/header.sqe
- addons/mission/config.cpp
- addons/mission/functions/fnc_timeUntilStart.sqf
- Move timeUntilStart to a function which does the global variant, and creates a local variant for each player. (There has been usecases for this)
- Moves all compositions into mods, automatically updated.
> Mission - Move Compositions and Time Until Start from template

- addons/mission/XEH_postInit.sqf
- Lets me define the params, finally found a use to it.
> Mission - Expand say3D

- AUTHORS.txt
- addons/mission/functions/fnc_collectIntel.sqf
- addons/mission/functions/fnc_groundFog.sqf
> Update author name

- addons/main/script_mod.hpp
- addons/mission_autotest/CfgEden.hpp
- title, mostly unused base classes and one required version issue.
> Update for HEMTT 1.16.2

- addons/apollo/functions/fnc_playerSingletonSave.sqf
- Mick says that the earplug issue came back, the function we used is gone in ACE now. We did eventually do the Todo.. 5 years later.
> Apollo - Fix lost earplugs issue

- addons/ui_tweaks/README.md
- addons/ui_tweaks/RscDisplay.hpp
- addons/ui_tweaks/config.cpp
- title, extends mission name/desc/image etc.
- Macro'd the values for ease.
> UI Tweaks - Extend mission loading screen

- addons/mission/compositions/contract_template/composition.sqe
- addons/supplies/functions/fnc_loadTraits.sqf
- addons/supplies/functions/fnc_medicalArsenal.sqf
- Composition now includes medic slots again.
- Old method of giving people medic trait has been disabled.
> Mission/Supplies - Format to new medic setup

- addons/cba_settings/cba_settings.sqf
- title
- Also does Enhanced movement for the trial run to cut down on fuckery.
> CBA Settings - Update IEDD Notebook & ACE Medical
